"use client";

import { useEffect, useMemo, useRef, useState } from "react";

const objects=[
  {id:"apple",picture:"🍎",label:"Apple"},{id:"ball",picture:"⚽",label:"Ball"},{id:"book",picture:"📕",label:"Book"},
  {id:"car",picture:"🚗",label:"Car"},{id:"clock",picture:"⏰",label:"Clock"},{id:"umbrella",picture:"☂️",label:"Umbrella"},
];
const orders=[[0,7,2,9,4,11,6,1,8,3,10,5],[5,0,8,2,7,10,1,9,4,6,3,11],[8,3,0,10,5,7,2,11,6,4,9,1]];

function MemoryGame(){
  const themes={fruits:{label:"🍎 Yummy Fruits",items:["🍎","🍌","🍇","🍊","🍓","🥑","🍍","🍒","🍑","🍐"]},animals:{label:"🦁 Friendly Animals",items:["🐶","🐱","🦁","🐷","🦊","🐼","🐯","🦒","🦓","🐘"]},space:{label:"🚀 Silly Space",items:["🚀","🛸","🪐","👨‍🚀","👾","🛰️","☄️","🌌","🔭","🌍"]}} as const;
  type Theme=keyof typeof themes;
  const [theme,setTheme]=useState<Theme>("fruits");const [seed,setSeed]=useState(0);const [open,setOpen]=useState<number[]>([]);const [matched,setMatched]=useState<number[]>([]);const [moves,setMoves]=useState(0);const [seconds,setSeconds]=useState(0);const [started,setStarted]=useState(false);const [locked,setLocked]=useState(false);const [won,setWon]=useState(false);
  const cards=useMemo(()=>[...themes[theme].items,...themes[theme].items].map((icon,index)=>({icon,id:index})).sort(()=>Math.random()-.5),[theme,seed]);
  const best=typeof window==="undefined"?null:localStorage.getItem("basha-match-best-"+theme);
  useEffect(()=>{if(!started||won)return;const timer=window.setInterval(()=>setSeconds(value=>value+1),1000);return()=>window.clearInterval(timer);},[started,won]);
  function reset(nextTheme:Theme=theme){setTheme(nextTheme);setSeed(value=>value+1);setOpen([]);setMatched([]);setMoves(0);setSeconds(0);setStarted(false);setLocked(false);setWon(false);}
  function flip(index:number){if(locked||open.includes(index)||matched.includes(index))return;setStarted(true);const next=[...open,index];setOpen(next);if(next.length!==2)return;setMoves(value=>value+1);setLocked(true);const [first,second]=next;if(cards[first].icon===cards[second].icon){window.setTimeout(()=>{const completed=[...matched,first,second];setMatched(completed);setOpen([]);setLocked(false);if(completed.length===cards.length){setWon(true);const current=Number(localStorage.getItem("basha-match-best-"+theme)||0);if(!current||moves+1<current)localStorage.setItem("basha-match-best-"+theme,String(moves+1));}},350);}else window.setTimeout(()=>{setOpen([]);setLocked(false);},800);}
  const total=themes[theme].items.length;const minutes=String(Math.floor(seconds/60)).padStart(2,"0"),secs=String(seconds%60).padStart(2,"0");
  return <article className="mini-game memory-game match-adventure"><div className="match-top"><div><small>GAME 5 · PICK A THEME</small><h3>Happy <em>Match</em> Adventure</h3><p>Tap two cards. Can you find the matching pictures? 🌈</p><b className="match-best">Best: {best?best+" moves":"--"}</b></div><div className="match-stats"><span><small>Moves</small><b>{moves}</b></span><span><small>Time</small><b>{minutes}:{secs}</b></span></div></div><div className="match-theme-tabs">{(Object.keys(themes) as Theme[]).map(key=><button key={key} className={theme===key?"active":""} onClick={()=>reset(key)}>{themes[key].label}</button>)}</div><div className="match-progress"><i style={{width:String(matched.length/cards.length*100)+"%"}}/></div><div className="memory-grid adventure-grid">{cards.map((card,index)=>{const visible=open.includes(index)||matched.includes(index);return <button key={card.id} className={(visible?"open ":"")+(matched.includes(index)?"matched":"")} onClick={()=>flip(index)} aria-label={visible?card.icon:"Hidden card"}><span className="card-back">⭐</span><span className="card-face"><b>{card.icon}</b></span></button>})}</div><div className="memory-status"><b>⭐ {matched.length/2} / {total} pairs</b><button onClick={()=>reset()}>Mix Again ↻</button></div>{won&&<div className="match-win" role="status"><span>👑</span><div><b>You did it!</b><p>You found every pair in {moves} moves.</p></div><button onClick={()=>reset()}>Play again 🎉</button></div>}</article>;
}

type SortCategory="fruits"|"vegetables"|"animals"|"household"|"school"|"vehicles";
type SortItem={id:string;picture:string;label:string;category:SortCategory};

const sortCategories:{id:SortCategory;label:string;telugu:string;hindi:string;icon:string}[]=[
  {id:"fruits",label:"Fruits",telugu:"పండ్లు",hindi:"फल",icon:"🍎"},
  {id:"vegetables",label:"Vegetables",telugu:"కూరగాయలు",hindi:"सब्ज़ियाँ",icon:"🥕"},
  {id:"animals",label:"Animals",telugu:"జంతువులు",hindi:"जानवर",icon:"🐘"},
  {id:"household",label:"Household",telugu:"ఇంటి వస్తువులు",hindi:"घर की चीज़ें",icon:"🪑"},
  {id:"school",label:"School",telugu:"పాఠశాల వస్తువులు",hindi:"स्कूल की चीज़ें",icon:"🎒"},
  {id:"vehicles",label:"Vehicles",telugu:"వాహనాలు",hindi:"वाहन",icon:"🚗"},
];
const sortItems:SortItem[]=[
  {id:"apple",picture:"🍎",label:"Apple",category:"fruits"},{id:"banana",picture:"🍌",label:"Banana",category:"fruits"},{id:"grapes",picture:"🍇",label:"Grapes",category:"fruits"},{id:"orange",picture:"🍊",label:"Orange",category:"fruits"},{id:"mango",picture:"🥭",label:"Mango",category:"fruits"},{id:"watermelon",picture:"🍉",label:"Watermelon",category:"fruits"},{id:"strawberry",picture:"🍓",label:"Strawberry",category:"fruits"},{id:"pear",picture:"🍐",label:"Pear",category:"fruits"},
  {id:"carrot",picture:"🥕",label:"Carrot",category:"vegetables"},{id:"corn",picture:"🌽",label:"Corn",category:"vegetables"},{id:"eggplant",picture:"🍆",label:"Eggplant",category:"vegetables"},{id:"tomato",picture:"🍅",label:"Tomato",category:"vegetables"},{id:"broccoli",picture:"🥦",label:"Broccoli",category:"vegetables"},{id:"cucumber",picture:"🥒",label:"Cucumber",category:"vegetables"},{id:"pepper",picture:"🫑",label:"Pepper",category:"vegetables"},{id:"potato",picture:"🥔",label:"Potato",category:"vegetables"},
  {id:"elephant",picture:"🐘",label:"Elephant",category:"animals"},{id:"turtle",picture:"🐢",label:"Turtle",category:"animals"},{id:"butterfly",picture:"🦋",label:"Butterfly",category:"animals"},{id:"lion",picture:"🦁",label:"Lion",category:"animals"},{id:"rabbit",picture:"🐇",label:"Rabbit",category:"animals"},{id:"dog",picture:"🐕",label:"Dog",category:"animals"},{id:"fish",picture:"🐟",label:"Fish",category:"animals"},{id:"owl",picture:"🦉",label:"Owl",category:"animals"},
  {id:"chair",picture:"🪑",label:"Chair",category:"household"},{id:"bed",picture:"🛏️",label:"Bed",category:"household"},{id:"lamp",picture:"💡",label:"Lamp",category:"household"},{id:"clock",picture:"⏰",label:"Clock",category:"household"},{id:"cup",picture:"🥤",label:"Cup",category:"household"},{id:"spoon",picture:"🥄",label:"Spoon",category:"household"},{id:"key",picture:"🔑",label:"Key",category:"household"},{id:"telephone",picture:"☎️",label:"Telephone",category:"household"},
  {id:"book",picture:"📕",label:"Book",category:"school"},{id:"pencil",picture:"✏️",label:"Pencil",category:"school"},{id:"backpack",picture:"🎒",label:"Backpack",category:"school"},{id:"ruler",picture:"📏",label:"Ruler",category:"school"},{id:"scissors",picture:"✂️",label:"Scissors",category:"school"},{id:"crayon",picture:"🖍️",label:"Crayon",category:"school"},{id:"notebook",picture:"📓",label:"Notebook",category:"school"},{id:"globe",picture:"🌐",label:"Globe",category:"school"},
  {id:"car",picture:"🚗",label:"Car",category:"vehicles"},{id:"bus",picture:"🚌",label:"Bus",category:"vehicles"},{id:"bicycle",picture:"🚲",label:"Bicycle",category:"vehicles"},{id:"train",picture:"🚂",label:"Train",category:"vehicles"},{id:"airplane",picture:"✈️",label:"Airplane",category:"vehicles"},{id:"boat",picture:"⛵",label:"Boat",category:"vehicles"},{id:"truck",picture:"🚚",label:"Truck",category:"vehicles"},{id:"scooter",picture:"🛴",label:"Scooter",category:"vehicles"},
];

function PictureSortingGame(){
  const [round,setRound]=useState(0);const [selected,setSelected]=useState<string|null>(null);const [placed,setPlaced]=useState<Record<string,SortCategory>>({});const [feedback,setFeedback]=useState("Choose a picture, then tap its group.");
  const items=useMemo(()=>{const chosen=sortCategories.flatMap((category,categoryIndex)=>{const group=sortItems.filter(item=>item.category===category.id);const start=(round*2+categoryIndex)%group.length;return [group[start],group[(start+3)%group.length]];});return chosen.map((_,index,array)=>array[(index*5+round*7)%array.length]);},[round]);const finished=Object.keys(placed).length===items.length;
  function chooseGroup(category:SortCategory){
    if(!selected||finished){setFeedback(selected?"Start a new round to play again.":"Choose a picture first.");return;}
    const item=sortItems.find(entry=>entry.id===selected);if(!item)return;
    if(item.category===category){setPlaced(value=>({...value,[item.id]:category}));setSelected(null);setFeedback(`✓ ${item.label} belongs in ${sortCategories.find(group=>group.id===category)?.label}.`);}
    else setFeedback("Not this group—try another one.");
  }
  function reset(){setRound(value=>value+1);setSelected(null);setPlaced({});setFeedback("Choose a picture, then tap its group.");}
  return <article className="mini-game sorting-game"><div className="sorting-head"><div><small>GAME 6 · PICTURE SORTING</small><h3>Which Group?</h3><p>Select each picture and place it with fruits, vegetables, animals, household items, school items, or vehicles. Every round brings a new mix.</p></div><b>⭐ {Object.keys(placed).length} / {items.length}</b></div><div className="sorting-items" aria-label="Pictures to sort">{items.map(item=>!placed[item.id]&&<button key={`${round}-${item.id}`} className={selected===item.id?"selected":""} onClick={()=>{setSelected(item.id);setFeedback(`Now choose the group for ${item.label}.`);}} aria-pressed={selected===item.id}><span>{item.picture}</span><b>{item.label}</b></button>)}</div><div className="sorting-bins">{sortCategories.map(category=><button key={category.id} className="sorting-bin" onClick={()=>chooseGroup(category.id)}><span className="sorting-bin-icon">{category.icon}</span><strong>{category.label}</strong><small>{category.telugu} · {category.hindi}</small><span className="sorting-placed">{items.filter(item=>placed[item.id]===category.id).map(item=><i key={item.id} title={item.label}>{item.picture}</i>)}</span></button>)}</div><div className={`sorting-feedback ${finished?"complete":""}`} aria-live="polite">{finished?"Great sorting! Every picture is in the right group.":feedback}</div><button className="sorting-reset" onClick={reset}>{finished?"New round →":"New picture mix ↻"}</button></article>;
}

const colors=["#ef4444","#f97316","#f6bd4b","#84cc16","#22b8a6","#38bdf8","#3b82f6","#6d5ce8","#ec79ad","#8b5e3c"];
const coloringAnimals=["Baby Cow","Tiger Cub","Little Giraffe","Sleepy Sloth","Beach Puppy","Baby Elephant","Happy Bunny","Little Lion","Baby Panda","Playful Monkey"] as const;
type ColoringAnimal=typeof coloringAnimals[number];

function CuteAnimalArt({animal,color,fills,setFills}:{animal:ColoringAnimal;color:string;fills:Record<string,string>;setFills:React.Dispatch<React.SetStateAction<Record<string,string>>>}){
  const fill=(part:string,base="#fff")=>fills[part]||base;
  const paint=(part:string,base="#fff")=>({className:"color-part",onClick:()=>setFills(value=>({...value,[part]:color})),fill:fill(part,base),stroke:"#26344f",strokeWidth:5,strokeLinecap:"round" as const,strokeLinejoin:"round" as const});
  const face=<><circle cx="225" cy="180" r="7" fill="#26344f"/><circle cx="285" cy="180" r="7" fill="#26344f"/><path d="M242 205q13 14 27 0" fill="none" stroke="#26344f" strokeWidth="5" strokeLinecap="round"/></>;
  return <svg viewBox="0 0 510 430" role="img" aria-label={`Interactive ${animal} coloring page`}>
    <circle {...paint("sun")} cx="73" cy="69" r="33"/><path d="M73 20v-15M73 133v-15M24 69H9m128 0h-15M38 34 27 23m81 81-11-11m0-59 11-11m-81 81 11-11" fill="none" stroke="#26344f" strokeWidth="4" strokeLinecap="round"/><path {...paint("cloud")} d="M375 70c9-30 50-30 60-2 28-9 49 11 47 36h-137c-1-22 12-35 30-34z"/><path d="M35 370q55-32 110 0t110 0 110 0 110 0" fill="none" stroke="#26344f" strokeWidth="4"/>
    {animal==="Baby Cow"&&<><ellipse {...paint("body")} cx="255" cy="295" rx="103" ry="87"/><path {...paint("left-ear")} d="M185 139q-61-35-76 6 25 39 78 25z"/><path {...paint("right-ear")} d="M325 139q61-35 76 6-25 39-78 25z"/><path {...paint("left-horn")} d="M199 124q-27-53 13-61 18 36 8 67z"/><path {...paint("right-horn")} d="M311 124q27-53-13-61-18 36-8 67z"/><circle {...paint("head")} cx="255" cy="174" r="91"/><ellipse {...paint("muzzle")} cx="255" cy="218" rx="55" ry="34"/><ellipse {...paint("spot1")} cx="213" cy="137" rx="29" ry="38"/><path {...paint("spot2")} d="M282 266q38-28 62 7-5 40-50 48z"/><circle cx="236" cy="218" r="5" fill="#26344f"/><circle cx="275" cy="218" r="5" fill="#26344f"/>{face}<path d="M185 348v31m51-24v31m39-31v31m49-38v31" stroke="#26344f" strokeWidth="9" strokeLinecap="round"/></>}
    {animal==="Tiger Cub"&&<><path {...paint("left-ear")} d="M172 126 130 73q58-8 81 37z"/><path {...paint("right-ear")} d="M338 126 380 73q-58-8-81 37z"/><ellipse {...paint("body")} cx="255" cy="303" rx="99" ry="84"/><circle {...paint("head")} cx="255" cy="177" r="98"/><ellipse {...paint("muzzle")} cx="255" cy="218" rx="48" ry="35"/>{face}<path d="M210 105l14 34m31-45v42m44-31-15 35M173 163l40 8m124-8-40 8M190 270l45 20m85-20-45 20m-82 52 44-16m80 17-43-16" fill="none" stroke="#26344f" strokeWidth="12" strokeLinecap="round"/><path d="M345 317q88-12 61 60-22 28-53 2" fill="none" stroke="#26344f" strokeWidth="12" strokeLinecap="round"/></>}
    {animal==="Little Giraffe"&&<><ellipse {...paint("body")} cx="260" cy="315" rx="91" ry="65"/><path {...paint("neck")} d="M211 304q20-121 25-174h65q-2 126 29 181z"/><path {...paint("left-ear")} d="M223 110q-60-30-63 13 28 29 68 15z"/><path {...paint("right-ear")} d="M305 110q60-30 63 13-28 29-68 15z"/><path d="M233 96V58m55 38V58" stroke="#26344f" strokeWidth="8" strokeLinecap="round"/><circle {...paint("horn1")} cx="233" cy="51" r="13"/><circle {...paint("horn2")} cx="288" cy="51" r="13"/><ellipse {...paint("head")} cx="260" cy="135" rx="65" ry="58"/>{face}{[[235,130],[280,155],[253,240],[294,277],[222,289],[273,328]].map(([x,y],i)=><circle key={i} {...paint(`spot${i}`)} cx={x} cy={y} r={i<2?11:16}/>)}<path d="M205 350v36m43-34v37m40-37v37m39-40v37" stroke="#26344f" strokeWidth="9" strokeLinecap="round"/></>}
    {animal==="Sleepy Sloth"&&<><path {...paint("branch","#fff")} d="M70 105q190 45 370-5l8 32q-188 64-387 4z"/><path d="M108 106q-15-46-44-55m302 58q23-42 61-58" fill="none" stroke="#26344f" strokeWidth="8" strokeLinecap="round"/><path {...paint("body")} d="M196 155q65-34 127 8 50 87-6 178-92 43-151-35-38-85 30-151z"/><path {...paint("arm1")} d="M212 169q-41-69-91-40-21 18 4 35 32-12 55 54z"/><path {...paint("arm2")} d="M298 169q41-69 91-40 21 18-4 35-32-12-55 54z"/><circle {...paint("head")} cx="255" cy="245" r="75"/><path {...paint("mask")} d="M190 234q25-62 65-29 40-33 65 29-21 77-65 75-44 2-65-75z"/>{face}<path d="M185 345q-39 23-55-6m195 4q44 20 57-12" fill="none" stroke="#26344f" strokeWidth="9" strokeLinecap="round"/></>}
    {animal==="Beach Puppy"&&<><path d="M40 329q50-24 100 0t100 0 100 0 100 0M35 357q40-20 80 0t80 0 80 0 80 0 80 0" fill="none" stroke="#26344f" strokeWidth="4"/><ellipse {...paint("float-ring")} cx="255" cy="320" rx="145" ry="62"/><ellipse cx="255" cy="320" rx="75" ry="25" fill="#fff" stroke="#26344f" strokeWidth="5"/><ellipse {...paint("body")} cx="255" cy="260" rx="77" ry="86"/><path {...paint("left-ear")} d="M201 153q-70-54-84 5 26 57 78 62z"/><path {...paint("right-ear")} d="M309 153q70-54 84 5-26 57-78 62z"/><circle {...paint("head")} cx="255" cy="176" r="82"/><ellipse {...paint("muzzle")} cx="255" cy="215" rx="44" ry="31"/>{face}<path {...paint("ball")} d="M407 303a36 36 0 1 0 0 72 36 36 0 0 0 0-72z"/><path d="M377 339h60m-30-36v72m-25-61 50 50" fill="none" stroke="#26344f" strokeWidth="4"/></>}
    {animal==="Baby Elephant"&&<><ellipse {...paint("body")} cx="255" cy="300" rx="112" ry="78"/><ellipse {...paint("left-ear")} cx="169" cy="176" rx="64" ry="78"/><ellipse {...paint("right-ear")} cx="341" cy="176" rx="64" ry="78"/><circle {...paint("head")} cx="255" cy="180" r="87"/><path {...paint("trunk")} d="M235 219q-1 95 39 105 42 5 48-35-24 17-36 1-7-45 3-72z"/>{face}<path d="M172 349v37m55-29v31m58-31v31m53-39v37" stroke="#26344f" strokeWidth="10" strokeLinecap="round"/><path {...paint("water")} d="M332 279q47-54 82-5-39 1-52 30 35-8 49 26-48 5-79-51z"/></>}
    {animal==="Happy Bunny"&&<><ellipse {...paint("body")} cx="255" cy="303" rx="94" ry="81"/><ellipse {...paint("ear1")} cx="209" cy="96" rx="34" ry="82" transform="rotate(-12 209 96)"/><ellipse {...paint("ear2")} cx="301" cy="96" rx="34" ry="82" transform="rotate(12 301 96)"/><circle {...paint("head")} cx="255" cy="190" r="87"/>{face}<path {...paint("belly")} d="M207 288q48-52 96 0v75h-96z"/><circle {...paint("tail")} cx="353" cy="316" r="31"/><path d="M247 201l8 8 8-8m-8 8v13" fill="none" stroke="#26344f" strokeWidth="4"/><path {...paint("carrot")} d="M111 260q53 6 61 61-53-7-61-61z"/><path d="M112 259q-16-35 8-49m-8 49q20-37 40-32" fill="none" stroke="#26344f" strokeWidth="6"/></>}
    {animal==="Little Lion"&&<><circle {...paint("mane")} cx="255" cy="176" r="114"/><ellipse {...paint("body")} cx="255" cy="310" rx="96" ry="76"/><circle {...paint("head")} cx="255" cy="177" r="79"/><circle {...paint("ear1")} cx="196" cy="124" r="30"/><circle {...paint("ear2")} cx="314" cy="124" r="30"/><ellipse {...paint("muzzle")} cx="255" cy="213" rx="47" ry="33"/>{face}<path d="M177 351v36m52-28v29m53-29v29m51-37v36M341 315q83-13 65 52" fill="none" stroke="#26344f" strokeWidth="10" strokeLinecap="round"/><circle {...paint("tail")} cx="405" cy="367" r="18"/></>}
    {animal==="Baby Panda"&&<><ellipse {...paint("body")} cx="255" cy="302" rx="101" ry="84"/><circle {...paint("ear1")} cx="190" cy="111" r="35"/><circle {...paint("ear2")} cx="320" cy="111" r="35"/><circle {...paint("head")} cx="255" cy="180" r="92"/><ellipse {...paint("patch1")} cx="218" cy="174" rx="25" ry="34" transform="rotate(25 218 174)"/><ellipse {...paint("patch2")} cx="292" cy="174" rx="25" ry="34" transform="rotate(-25 292 174)"/>{face}<ellipse {...paint("belly")} cx="255" cy="310" rx="53" ry="56"/><path {...paint("bamboo")} d="M116 334 152 119l18 3-36 215z"/><path d="M143 168q-47-33-57-5 29 28 54 20m-7 55q-54-24-59 8 39 20 55 6" fill="none" stroke="#26344f" strokeWidth="7"/></>}
    {animal==="Playful Monkey"&&<><path {...paint("tail")} d="M335 305q112 7 70-79-24-33-48-5 47 36 8 64z"/><ellipse {...paint("body")} cx="255" cy="300" rx="91" ry="79"/><circle {...paint("ear1")} cx="168" cy="174" r="41"/><circle {...paint("ear2")} cx="342" cy="174" r="41"/><circle {...paint("head")} cx="255" cy="177" r="84"/><path {...paint("face")} d="M191 177q14-69 64-34 50-35 64 34-2 79-64 82-62-3-64-82z"/>{face}<path d="M187 347v39m45-31v33m54-33v33m40-41v39" stroke="#26344f" strokeWidth="10" strokeLinecap="round"/><path {...paint("banana")} d="M94 270q36 51 87 10-24 76-87 45-31-17 0-55z"/></>}
  </svg>;
}

const coloringPages=[
  {name:"Baby Cow",src:"/coloring/original/cow.png"},{name:"Tiger Cub",src:"/coloring/original/tiger.png"},{name:"Little Giraffe",src:"/coloring/original/giraffe.png"},{name:"Happy Seahorse",src:"/coloring/original/seahorse.png"},{name:"Friendly Dinosaur",src:"/coloring/original/dinosaur.png"},{name:"Smiling Shark",src:"/coloring/original/shark.png"},{name:"Jolly Jellyfish",src:"/coloring/original/jellyfish.png"},{name:"Little Turtle",src:"/coloring/original/turtle.png"},{name:"Sleepy Sloth",src:"/coloring/original/sloth.png"},{name:"Baby Elephant",src:"/coloring/original/elephant.png"},
];

function ColoringGame(){
  const [color,setColor]=useState(colors[0]);const [page,setPage]=useState(0);const canvasRef=useRef<HTMLCanvasElement>(null);const imageRef=useRef<HTMLImageElement|null>(null);const item=coloringPages[page];
  function drawPage(){const canvas=canvasRef.current;if(!canvas)return;const image=new Image();image.onload=()=>{const scale=Math.min(760/image.naturalWidth,820/image.naturalHeight,1);canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);const context=canvas.getContext("2d",{willReadFrequently:true});if(!context)return;context.fillStyle="#fff";context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);imageRef.current=image;};image.src=item.src;}
  useEffect(()=>{drawPage();},[page]);
  function paint(event:React.PointerEvent<HTMLCanvasElement>){const canvas=canvasRef.current;const context=canvas?.getContext("2d",{willReadFrequently:true});if(!canvas||!context)return;const rect=canvas.getBoundingClientRect();let x=Math.floor((event.clientX-rect.left)*canvas.width/rect.width),y=Math.floor((event.clientY-rect.top)*canvas.height/rect.height);const data=context.getImageData(0,0,canvas.width,canvas.height);const brightness=(px:number,py:number)=>{const offset=(py*canvas.width+px)*4;return(data.data[offset]+data.data[offset+1]+data.data[offset+2])/3};if(brightness(x,y)<72){let best={x,y,light:brightness(x,y)};for(let radius=1;radius<=14&&best.light<72;radius++){for(let dy=-radius;dy<=radius;dy++){for(let dx=-radius;dx<=radius;dx++){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=canvas.width||ny>=canvas.height)continue;const light=brightness(nx,ny);if(light>best.light)best={x:nx,y:ny,light};}}}if(best.light<72)return;x=best.x;y=best.y;}const start=(y*canvas.width+x)*4;const sr=data.data[start],sg=data.data[start+1],sb=data.data[start+2];const rgb=color.match(/[a-f\d]{2}/gi)?.map(value=>parseInt(value,16));if(!rgb)return;const visited=new Uint8Array(canvas.width*canvas.height);const stack=[y*canvas.width+x];while(stack.length){const pos=stack.pop()!;if(visited[pos])continue;visited[pos]=1;const offset=pos*4,r=data.data[offset],g=data.data[offset+1],b=data.data[offset+2];const light=(r+g+b)/3;const distance=Math.abs(r-sr)+Math.abs(g-sg)+Math.abs(b-sb);if(light<72||distance>210)continue;data.data[offset]=rgb[0];data.data[offset+1]=rgb[1];data.data[offset+2]=rgb[2];const px=pos%canvas.width,py=Math.floor(pos/canvas.width);if(px>0)stack.push(pos-1);if(px<canvas.width-1)stack.push(pos+1);if(py>0)stack.push(pos-canvas.width);if(py<canvas.height-1)stack.push(pos+canvas.width);}context.putImageData(data,0,0);}
  function choosePage(index:number){setPage(index)}
  return <article className="mini-game coloring-game"><div className="mini-game-head"><div><small>GAME 6 · 10 ORIGINAL COLORING PAGES</small><h3>Cute Coloring Gallery</h3><p>Choose a picture, pick a colored pencil, then tap inside a white area.</p></div><button className="clear-color" onClick={drawPage}>Clear page ↻</button></div><div className="coloring-tabs" role="group" aria-label="Choose a coloring page">{coloringPages.map((entry,index)=><button key={entry.name} className={page===index?"active":""} onClick={()=>choosePage(index)}><img src={entry.src} alt=""/><small>{entry.name}</small></button>)}</div><div className="coloring-title"><b>{item.name}</b><span>Page {page+1} of {coloringPages.length}</span></div><div className="coloring-workspace"><div className="coloring-board"><canvas ref={canvasRef} onPointerDown={paint} role="img" aria-label={`Interactive ${item.name} coloring page`}/></div><aside className="pencil-palette" aria-label="Choose a colored pencil"><small>Pick a pencil</small><div>{colors.map(value=><button key={value} className={color===value?"active":""} style={{"--pencil-color":value} as React.CSSProperties} onClick={()=>setColor(value)} aria-label={`Choose ${value} pencil`}><span/></button>)}</div></aside></div><div className="coloring-nav"><button onClick={()=>choosePage((page-1+coloringPages.length)%coloringPages.length)}>← Previous picture</button><button onClick={()=>choosePage((page+1)%coloringPages.length)}>Next picture →</button></div></article>;
}

type FoodCard={english:string;roman:string;telugu:string;picture:string};
const foodCards:Record<"Vegetables"|"Fruits",FoodCard[]>={
  Vegetables:[
    {english:"Potato",roman:"algadda",telugu:"ఆల్గడ్డ",picture:"🥔"},{english:"Tindora",roman:"donadakaaya",telugu:"దొండకాయ",picture:"🥒"},{english:"Yellow cucumber",roman:"dosakaaya / budamakaaya",telugu:"దోసకాయ / బుదమకాయ",picture:"🥒"},{english:"Drumstick",roman:"munagakaaya",telugu:"మునగకాయ",picture:"🌿"},{english:"Corn",roman:"makkajonna / jonnakankulu",telugu:"కంకి / కంకులు / జొన్నలు / మక్కబుట్ట / మక్కజొన్న",picture:"🌽"},{english:"Onion",roman:"ulligadda",telugu:"ఉల్లిగడ్డ",picture:"🧅"},{english:"Okra",roman:"bendakaaya",telugu:"బెండకాయ",picture:"🌱"},{english:"Bottle gourd",roman:"sorakaaya",telugu:"సొరకాయ",picture:"🍐"},{english:"Bitter gourd",roman:"kaakarkaaya",telugu:"కాకరకాయ",picture:"🥒"},{english:"Snake gourd",roman:"potlakaaya",telugu:"పొట్లకాయ",picture:"🥒"},{english:"Ridge gourd",roman:"beerakaaya",telugu:"బీరకాయ",picture:"🥒"},{english:"Pumpkin",roman:"gummadikaaya",telugu:"గుమ్మడికాయ",picture:"🎃"},{english:"Yam",roman:"kandagadda",telugu:"కందగడ్డ",picture:"🍠"},{english:"Cabbage",roman:"kyaabej",telugu:"క్యాబేజీ",picture:"🥬"},{english:"Chilli pepper",roman:"mirapakaaya",telugu:"మిరపకాయ",picture:"🌶️"},{english:"Eggplant",roman:"vankaaya",telugu:"వంకాయ",picture:"🍆"},{english:"Cauliflower",roman:"kaaliphlavar",telugu:"కాలీఫ్లవర్",picture:"🥦"},{english:"Green beans",roman:"chikkudukaaya",telugu:"చిక్కుడుకాయ",picture:"🫛"},{english:"Bell pepper",roman:"kyapsicum / capsicum",telugu:"క్యాప్సికం",picture:"🫑"},
  ],
  Fruits:[
    {english:"Apple",roman:"apple pandu",telugu:"ఆపిల్ పండు",picture:"🍎"},{english:"Banana",roman:"arati pandu",telugu:"అరటి పండు",picture:"🍌"},{english:"Orange",roman:"naranja",telugu:"నారింజ",picture:"🍊"},{english:"Mango",roman:"maamidi pandu",telugu:"మామిడి పండు",picture:"🥭"},{english:"Custard apple",roman:"seethaphalam",telugu:"సీతాఫలం",picture:"🍈"},{english:"Grapes",roman:"draksha pallu",telugu:"ద్రాక్ష పళ్ళు",picture:"🍇"},{english:"Pomegranate",roman:"danimma",telugu:"దానిమ్మ",picture:"🔴"},{english:"Lemon",roman:"nimma kaaya",telugu:"నిమ్మకాయ",picture:"🍋"},{english:"Lime",roman:"nimma kaaya",telugu:"నిమ్మకాయ",picture:"🟢"},{english:"Chikoo",roman:"sapota",telugu:"చీకూ",picture:"🥝"},{english:"Strawberry",roman:"straberri",telugu:"స్ట్రాబెర్రీ",picture:"🍓"},{english:"Tomato",roman:"tamata",telugu:"టమాటా",picture:"🍅"},{english:"Jackfruit",roman:"panasa pandu",telugu:"పనస పండు",picture:"🍈"},{english:"Jamun",roman:"neredu pallu",telugu:"నేరేడు పళ్ళు",picture:"🫐"},{english:"Papaya",roman:"boppayi",telugu:"బొప్పాయి",picture:"🧡"},{english:"Guava",roman:"jaama kaaya",telugu:"జామకాయ",picture:"🍐"},{english:"Coconut",roman:"kobbari kaaya",telugu:"కొబ్బరికాయ",picture:"🥥"},{english:"Watermelon",roman:"pucchakaaya",telugu:"పుచ్చకాయ",picture:"🍉"},{english:"Batai",roman:"batai",telugu:"బటాయి / బటై",picture:"🍊"},{english:"Mulberry",roman:"malbari",telugu:"మల్బరీ",picture:"🫐"},{english:"Lychee",roman:"lichi",telugu:"లీచీ",picture:"🔴"},{english:"Cantaloupe",roman:"karbooza",telugu:"కర్బూజా",picture:"🍈"},{english:"Plantain",roman:"arati kaaya",telugu:"అరటికాయ",picture:"🍌"},
  ],
};

function FoodDeck({category}:{category:"Vegetables"|"Fruits"}){
  const [round,setRound]=useState(0);const [seed,setSeed]=useState(0);const [score,setScore]=useState(0);const [feedback,setFeedback]=useState<"idle"|"correct"|"wrong">("idle");const [wrong,setWrong]=useState("");
  const source=foodCards[category];const target=source[round%source.length];
  const choices=useMemo(()=>{const picked=[target];for(let step=1;picked.length<6;step++){const candidate=source[(round+step*5+seed*3)%source.length];if(!picked.some(item=>item.english===candidate.english))picked.push(candidate);}for(let i=picked.length-1;i>0;i--){const j=(i*7+round*3+seed*11)%(i+1);[picked[i],picked[j]]=[picked[j],picked[i]];}return picked;},[category,round,seed,target]);
  function choose(item:FoodCard){if(feedback==="correct")return;if(item.english===target.english){setFeedback("correct");setScore(value=>value+1);setTimeout(()=>{setRound(value=>value+1);setSeed(value=>value+1);setFeedback("idle");setWrong("");},900);}else{setWrong(item.english);setFeedback("wrong");setTimeout(()=>{setFeedback("idle");setWrong("");},550);}}
  return <section className={`food-deck shuffle-game ${category.toLowerCase()}`} aria-label={`${category} Telugu shuffle game`}><div className="food-deck-head"><div><span>{category==="Vegetables"?"🥕":"🍎"}</span><div><small>{category.toUpperCase()} SHUFFLE GAME</small><h4>{category==="Vegetables"?"కూరగాయలు":"పండ్లు"}</h4></div></div><b>⭐ {score} stars</b></div><div className="shuffle-stage"><div className="shuffle-clue"><small>FIND THE TELUGU WORD</small><span>{target.picture}</span><h5>{target.english}</h5><i>[{target.roman}]</i></div><div className="word-choice-grid" aria-label={`Find ${target.english} in Telugu`}>{choices.map((item,index)=><button key={`${round}-${seed}-${item.english}`} className={`${wrong===item.english?"wrong":""} ${feedback==="correct"&&item.english===target.english?"correct":""}`} style={{"--delay":`${index*.06}s`} as React.CSSProperties} onClick={()=>choose(item)}><b>{item.telugu}</b><small>{feedback==="correct"&&item.english===target.english?item.english:"Tap to choose"}</small></button>)}</div></div><div className={`shuffle-feedback ${feedback}`} aria-live="polite">{feedback==="correct"?`✨ Correct! ${target.telugu}`:feedback==="wrong"?"Try another card!":"The cards move every round—look carefully."}</div><div className="vocab-actions"><span>Round {round+1}</span><button className="shuffle-button" onClick={()=>{setSeed(value=>value+1);setFeedback("idle");setWrong("");}}>⤨ Shuffle cards</button><button onClick={()=>{setRound(value=>value+1);setSeed(value=>value+1);setFeedback("idle");setWrong("");}}>New word →</button></div></section>;
}

function VocabularyShuffle(){return <article className="vocab-game"><div className="vocab-head"><div><small>GAME 7 · TELUGU WORD SHUFFLE</small><h3>Shuffle, Find &amp; Learn</h3><p>Look at the picture and English clue, then find the matching Telugu word after the cards shuffle.</p></div></div><FoodDeck category="Vegetables"/><FoodDeck category="Fruits"/></article>}

type ActionCard={english:string;emoji:string;telugu:string;teluguPhonetic:string;hindi:string;hindiPhonetic:string;group:"Daily routine"|"Play & move"|"Learn & create"};
const actionCards:ActionCard[]=[
  {english:"Eat",emoji:"🍎",telugu:"తిను",teluguPhonetic:"Tinu",hindi:"खाना",hindiPhonetic:"Khana",group:"Daily routine"},
  {english:"Drink",emoji:"🥛",telugu:"తాగు",teluguPhonetic:"Taagu",hindi:"पीना",hindiPhonetic:"Peena",group:"Daily routine"},
  {english:"Sleep",emoji:"😴",telugu:"పడుకో / నిద్రపో",teluguPhonetic:"Paduko / Nidrapo",hindi:"सोना",hindiPhonetic:"Sona",group:"Daily routine"},
  {english:"Wash",emoji:"🧼",telugu:"కడుగు",teluguPhonetic:"Kadugu",hindi:"धोना",hindiPhonetic:"Dhona",group:"Daily routine"},
  {english:"Smile",emoji:"😊",telugu:"చిరునవ్వు",teluguPhonetic:"Chirunavvu",hindi:"मुस्कुराना",hindiPhonetic:"Muskurana",group:"Daily routine"},
  {english:"Run",emoji:"🏃",telugu:"పరిగెత్తు",teluguPhonetic:"Parigettu",hindi:"दौड़ना",hindiPhonetic:"Daudna",group:"Play & move"},
  {english:"Jump",emoji:"🦘",telugu:"దూకు",teluguPhonetic:"Dooku",hindi:"कूदना",hindiPhonetic:"Koodna",group:"Play & move"},
  {english:"Play",emoji:"🧩",telugu:"ఆడుకో",teluguPhonetic:"Aaduko",hindi:"खेलना",hindiPhonetic:"Khelna",group:"Play & move"},
  {english:"Sing",emoji:"🎤",telugu:"పాడు",teluguPhonetic:"Paadu",hindi:"गाना",hindiPhonetic:"Gaana",group:"Play & move"},
  {english:"Dance",emoji:"💃",telugu:"నాట్యం చేయి",teluguPhonetic:"Naatyam cheyi",hindi:"नाचना",hindiPhonetic:"Naachna",group:"Play & move"},
  {english:"Laugh",emoji:"😄",telugu:"నవ్వు",teluguPhonetic:"Navvu",hindi:"हंसना",hindiPhonetic:"Hansna",group:"Play & move"},
  {english:"Read",emoji:"📚",telugu:"చదువు",teluguPhonetic:"Chaduvu",hindi:"पढ़ना",hindiPhonetic:"Padhna",group:"Learn & create"},
  {english:"Write",emoji:"✏️",telugu:"రాయి",teluguPhonetic:"Raayi",hindi:"लिखना",hindiPhonetic:"Likhna",group:"Learn & create"},
  {english:"Draw",emoji:"🎨",telugu:"బొమ్మ గీయి",teluguPhonetic:"Bomma geeyi",hindi:"चित्र बनाना",hindiPhonetic:"Chitra banana",group:"Learn & create"},
  {english:"Listen",emoji:"👂",telugu:"విను",teluguPhonetic:"Vinu",hindi:"सुनना",hindiPhonetic:"Sunna",group:"Learn & create"},
  {english:"Speak",emoji:"🗣️",telugu:"మాట్లాడు",teluguPhonetic:"Maatlaadu",hindi:"बोलना",hindiPhonetic:"Bolna",group:"Learn & create"},
];

function ActionFlashcards(){
  const [group,setGroup]=useState<"All"|ActionCard["group"]>("All");const [flipped,setFlipped]=useState<string[]>([]);const [seed,setSeed]=useState(0);
  const shown=useMemo(()=>{const filtered=group==="All"?actionCards:actionCards.filter(item=>item.group===group);const shift=seed%filtered.length;return [...filtered.slice(shift),...filtered.slice(0,shift)];},[group,seed]);
  function toggle(word:string){setFlipped(value=>value.includes(word)?value.filter(item=>item!==word):[...value,word]);}
  function chooseGroup(next:"All"|ActionCard["group"]){setGroup(next);setFlipped([]);setSeed(0);}
  return <article className="action-game"><div className="action-head"><div><small>GAME 8 · BILINGUAL ACTION FLASHCARDS</small><h3>See it. Flip it. Say it!</h3><p>Tap an English action to reveal its Telugu and Hindi words. Natural voice recordings can be added later.</p></div><button onClick={()=>{setSeed(value=>value+3);setFlipped([])}}>⤨ Shuffle cards</button></div><div className="action-filters" role="group" aria-label="Filter action cards">{(["All","Daily routine","Play & move","Learn & create"] as const).map(item=><button key={item} className={group===item?"active":""} onClick={()=>chooseGroup(item)}>{item}</button>)}</div><div className="action-grid">{shown.map((item,index)=><button key={`${seed}-${item.english}`} className={`action-card ${flipped.includes(item.english)?"flipped":""}`} style={{"--delay":`${index*.035}s`} as React.CSSProperties} onClick={()=>toggle(item.english)} aria-label={`${item.english}: tap to show Telugu and Hindi`} aria-pressed={flipped.includes(item.english)}><span className="action-card-inner"><span className="action-front"><i>{item.emoji}</i><b>{item.english}</b><small>{item.group}</small><em>Tap for Telugu + Hindi ↻</em></span><span className="action-back"><span className="action-back-title"><b>{item.english}</b><i>{item.emoji}</i></span><span className="action-translation telugu"><small>తెలుగు · TELUGU</small><b>{item.telugu}</b><i>{item.teluguPhonetic}</i><em>🔊 Telugu voice · upload later</em></span><span className="action-translation hindi"><small>हिंदी · HINDI</small><b>{item.hindi}</b><i>{item.hindiPhonetic}</i><em>🔊 Hindi voice · upload later</em></span><strong>Tap to turn back ↻</strong></span></span></button>)}</div></article>;
}

type RainLanguage="Telugu"|"Hindi";
type RainGroup="Vowels"|"Consonants";
const rainLetters:Record<RainLanguage,Record<RainGroup,string[]>>={
  Telugu:{Vowels:["అ","ఆ","ఇ","ఈ","ఉ","ఊ","ఋ","ఎ","ఏ","ఐ","ఒ","ఓ","ఔ","అం","అః"],Consonants:["క","ఖ","గ","ఘ","చ","ఛ","జ","ఝ","ట","ఠ","డ","ఢ","త","థ","ద","ధ","న","ప","ఫ","బ","భ","మ","య","ర","ల","వ","శ","ష","స","హ"]},
  Hindi:{Vowels:["अ","आ","इ","ई","उ","ऊ","ऋ","ए","ऐ","ओ","औ","अं","अः"],Consonants:["क","ख","ग","घ","च","छ","ज","झ","ट","ठ","ड","ढ","त","थ","द","ध","न","प","फ","ब","भ","म","य","र","ल","व","श","ष","स","ह"]},
};

function LetterRain(){
  const [language,setLanguage]=useState<RainLanguage>("Telugu");const [group,setGroup]=useState<RainGroup>("Vowels");const [round,setRound]=useState(0);const [score,setScore]=useState(0);const [feedback,setFeedback]=useState("Tap the matching falling letter.");
  const source=rainLetters[language][group];const target=source[(round*5+2)%source.length];const targetIndex=(round*3+1)%6;
  const drops=useMemo(()=>Array.from({length:6},(_,index)=>index===targetIndex?target:source[(round*7+index*3+4)%source.length]),[language,group,round,target,targetIndex,source]);
  function restart(nextLanguage=language,nextGroup=group){setLanguage(nextLanguage);setGroup(nextGroup);setRound(0);setScore(0);setFeedback("Tap the matching falling letter.");}
  function next(message:string){setFeedback(message);setTimeout(()=>{setRound(value=>value+1);setFeedback("Tap the matching falling letter.");},500);}
  function choose(letter:string){if(feedback!=="Tap the matching falling letter.")return;if(letter===target){setScore(value=>value+1);next("✓ Correct!");}else{setFeedback("Try another falling letter.");setTimeout(()=>setFeedback("Tap the matching falling letter."),450);}}
  function missed(){if(feedback==="Tap the matching falling letter.")next("The letter passed—try the next one.");}
  return <article className="letter-rain-game"><div className="letter-rain-head"><div><small>GAME 9 · SILENT LETTER RECOGNITION</small><h3>Letter Rain</h3><p>Find and tap the requested letter before it reaches the bottom.</p></div><b>⭐ {score} points</b></div><div className="rain-controls"><div>{(["Telugu","Hindi"] as const).map(item=><button key={item} className={language===item?"active":""} onClick={()=>restart(item,group)}>{item==="Telugu"?"తెలుగు":"हिन्दी"}</button>)}</div><div>{(["Vowels","Consonants"] as const).map(item=><button key={item} className={group===item?"active":""} onClick={()=>restart(language,item)}>{item}</button>)}</div></div><div className="rain-target">Tap <strong>{target}</strong></div><div className="rain-sky" key={`${language}-${group}-${round}`} aria-label={`Tap the falling letter ${target}`}>{drops.map((letter,index)=><button key={`${round}-${index}-${letter}`} style={{"--rain-left":`${8+index*16}%`,"--rain-delay":`${(index%3)*.35}s`,"--rain-speed":`${5.8+(index%2)*.7}s`} as React.CSSProperties} onClick={()=>choose(letter)} onAnimationEnd={index===targetIndex?missed:undefined} aria-label={`Falling letter ${letter}`}>{letter}</button>)}</div><div className="rain-feedback" aria-live="polite">{feedback}</div><button className="rain-next" onClick={()=>{setRound(value=>value+1);setFeedback("Tap the matching falling letter.");}}>New letter →</button></article>;
}

export default function MoreGames(){return <section className="more-games" id="more-games"><div className="section-title"><p className="kicker"><b>✦</b> More playful practice</p><h2>Remember it.<br/><em>Sort it correctly.</em></h2><p>Short games for visual memory, word recognition, language practice, and careful thinking.</p></div><div className="more-games-grid"><MemoryGame/><PictureSortingGame/></div><VocabularyShuffle/><ActionFlashcards/><LetterRain/></section>}
