"use client";

import { useEffect, useRef, useState } from "react";

type Language = "Telugu" | "Hindi";
type LocalStory = { title: string; teaser: string; pages: string[]; moral: string; question: string; audio?: string[] };
type Story = { id: string; theme: string; minutes: number; Telugu: LocalStory; Hindi: LocalStory };

const stories: Story[] = [
  { id:"lion-mouse", theme:"Kindness", minutes:3,
    Telugu:{title:"సింహం మరియు ఎలుక",teaser:"ఒక చిన్న సహాయం పెద్ద స్నేహంగా మారింది.",pages:["అడవిలో నిద్రపోతున్న సింహం మీదుగా ఒక చిన్న ఎలుక పరుగెత్తింది. సింహం కోపంగా దానిని తన పెద్ద పంజాలో పట్టుకుంది.","‘నన్ను వదిలేయండి. ఏదో ఒక రోజు నేను మీకు సహాయం చేస్తాను,’ అంది ఎలుక. సింహం నవ్వినా, దయతో దానిని విడిచిపెట్టింది.","కొన్ని రోజుల తరువాత సింహం వేటగాడి వలలో చిక్కుకుంది. దాని గర్జన విన్న ఎలుక వెంటనే వచ్చి తాళ్లను తన పదునైన పళ్లతో కొరికింది.","వల తెగిపోయింది. సింహం బయటపడింది. చిన్న స్నేహితుడి సహాయం ఎంత గొప్పదో అది తెలుసుకుంది."],moral:"ఎవరూ సహాయం చేయలేనంత చిన్నవారు కాదు.",question:"ఎలుక ధైర్యంగా సింహానికి ఎలా సహాయం చేసింది?",audio:["/audio/stories/lion-mouse-telugu-1.wav","/audio/stories/lion-mouse-telugu-2.wav","/audio/stories/lion-mouse-telugu-3.wav","/audio/stories/lion-mouse-telugu-4.wav","/audio/stories/lion-mouse-telugu-ending.wav"]},
    Hindi:{title:"शेर और चूहा",teaser:"एक छोटी-सी मदद बड़ी दोस्ती बन गई।",pages:["जंगल में सो रहे शेर के ऊपर एक छोटा चूहा दौड़ गया। शेर ने क्रोध में उसे अपने बड़े पंजे में पकड़ लिया।","चूहे ने कहा, ‘मुझे छोड़ दीजिए। शायद किसी दिन मैं आपकी सहायता करूँ।’ शेर हँसा, फिर दया करके उसे जाने दिया।","कुछ दिनों बाद शेर शिकारी के जाल में फँस गया। उसकी दहाड़ सुनकर चूहा आया और रस्सियाँ अपने तेज दाँतों से काटने लगा।","जाल टूट गया और शेर मुक्त हो गया। उसने समझा कि छोटा मित्र भी बहुत बड़ी सहायता कर सकता है।"],moral:"कोई भी मदद करने के लिए बहुत छोटा नहीं होता।",question:"चूहे ने साहस दिखाकर शेर की मदद कैसे की?",audio:["/audio/stories/lion-mouse-hindi-1.wav","/audio/stories/lion-mouse-hindi-2.wav","/audio/stories/lion-mouse-hindi-3.wav","/audio/stories/lion-mouse-hindi-4.wav","/audio/stories/lion-mouse-hindi-ending.wav"]}},
  { id:"tortoise-hare", theme:"Perseverance", minutes:3,
    Telugu:{title:"కుందేలు మరియు తాబేలు",teaser:"వేగం కంటే పట్టుదల గెలిచిన పరుగు.",pages:["తాను అడవిలో అందరికంటే వేగంగా పరుగెత్తగలనని కుందేలు ఎప్పుడూ గొప్పలు చెప్పేది. నెమ్మదిగా నడిచే తాబేలును చూసి నవ్వేది.","తాబేలు ప్రశాంతంగా, ‘మనిద్దరం పరుగు పందెం చేద్దామా?’ అంది. పందెం మొదలవగానే కుందేలు దూరంగా దూసుకెళ్లింది.","తాబేలు చాలా వెనుక ఉందని భావించి కుందేలు చెట్టు కింద నిద్రపోయింది. తాబేలు మాత్రం ఒక్క అడుగు కూడా ఆపకుండా ముందుకు సాగింది.","కుందేలు మేల్కొని పరుగెత్తేలోపే తాబేలు గమ్యాన్ని చేరింది. అడవంతా దాని ఓర్పును అభినందించింది."],moral:"నిదానమైనా నిరంతర ప్రయత్నం విజయాన్ని ఇస్తుంది.",question:"తాబేలు ఎందుకు గెలిచింది?",audio:["/audio/stories/tortoise-hare-telugu-1.wav","/audio/stories/tortoise-hare-telugu-2.wav","/audio/stories/tortoise-hare-telugu-3.wav","/audio/stories/tortoise-hare-telugu-4.wav","/audio/stories/tortoise-hare-telugu-ending.wav"]},
    Hindi:{title:"खरगोश और कछुआ",teaser:"तेज़ी नहीं, लगातार कोशिश ने दौड़ जीती।",pages:["खरगोश हमेशा कहता था कि वह जंगल में सबसे तेज दौड़ता है। वह धीरे चलने वाले कछुए का मज़ाक उड़ाता था।","कछुए ने शांत होकर कहा, ‘क्या हम दौड़ लगाएँ?’ दौड़ शुरू होते ही खरगोश बहुत आगे निकल गया।","कछुआ बहुत पीछे है, यह सोचकर खरगोश पेड़ के नीचे सो गया। कछुआ बिना रुके एक-एक कदम चलता रहा।","खरगोश जागकर दौड़ा, लेकिन कछुआ लक्ष्य तक पहुँच चुका था। सबने उसके धैर्य की प्रशंसा की।"],moral:"धीरे लेकिन लगातार किया गया प्रयास सफलता देता है।",question:"कछुआ दौड़ क्यों जीत पाया?",audio:["/audio/stories/tortoise-hare-hindi-1.wav","/audio/stories/tortoise-hare-hindi-2.wav","/audio/stories/tortoise-hare-hindi-3.wav","/audio/stories/tortoise-hare-hindi-4.wav","/audio/stories/tortoise-hare-hindi-ending.wav"]}},
  { id:"fox-grapes", theme:"Honesty", minutes:3,
    Telugu:{title:"నక్క మరియు ద్రాక్ష",teaser:"అందని దానిని తక్కువ చేయడం సరైనదా?",pages:["ఎండలో నడిచిన నక్కకు చాలా దాహం వేసింది. ఒక తీగకు వేలాడుతున్న ఊదా ద్రాక్ష గుత్తిని చూసింది.","అది పైకి ఎగిరింది, కానీ ద్రాక్ష అందలేదు. మళ్లీ మళ్లీ ప్రయత్నించినా ప్రతి సారి కొద్దిగా దూరంలోనే ఆగిపోయింది.","అలసిపోయిన నక్క, ‘ఆ ద్రాక్ష పుల్లగా ఉంటుంది. నాకు అసలు వద్దు,’ అంటూ వెనుదిరిగింది.","కొమ్మపై ఉన్న పిట్ట నక్క మాట విని చిరునవ్వు నవ్వింది. ప్రయత్నం విఫలమైందని నిజం చెప్పడం కూడా ధైర్యమే."],moral:"అందని దానిని చెడ్డదని చెప్పకూడదు.",question:"నక్క నిజంగా ద్రాక్షను ఎందుకు వద్దనుకుంది?",audio:["/audio/stories/fox-grapes-telugu-1.wav","/audio/stories/fox-grapes-telugu-2.wav","/audio/stories/fox-grapes-telugu-3.wav","/audio/stories/fox-grapes-telugu-4.wav","/audio/stories/fox-grapes-telugu-ending.wav"]},
    Hindi:{title:"लोमड़ी और अंगूर",teaser:"जो न मिले, क्या उसे बुरा कहना ठीक है?",pages:["धूप में चलते-चलते लोमड़ी को बहुत प्यास लगी। उसने बेल पर बैंगनी अंगूरों का गुच्छा देखा।","वह उछली, पर अंगूर नहीं मिले। उसने बार-बार कोशिश की, लेकिन हर बार वे थोड़े दूर रह गए।","थककर लोमड़ी बोली, ‘ये अंगूर खट्टे होंगे। मुझे चाहिए ही नहीं,’ और चली गई।","डाली पर बैठी चिड़िया मुस्कराई। कोशिश सफल न हुई, यह सच मान लेना भी साहस है।"],moral:"जो न मिले, उसे बुरा बताकर मन नहीं बहलाना चाहिए।",question:"लोमड़ी ने अंगूरों को खट्टा क्यों कहा?",audio:["/audio/stories/fox-grapes-hindi-1.wav","/audio/stories/fox-grapes-hindi-2.wav","/audio/stories/fox-grapes-hindi-3.wav","/audio/stories/fox-grapes-hindi-4.wav","/audio/stories/fox-grapes-hindi-ending.wav"]}},
  { id:"boy-wolf", theme:"Honesty", minutes:4,
    Telugu:{title:"తోడేలు వచ్చిందన్న బాలుడు",teaser:"అబద్ధపు కేక నిజమైన ప్రమాదాన్ని తెచ్చింది.",pages:["ఒక కాపరి బాలుడు రోజూ గొర్రెలను కొండపై మేపేవాడు. ఒంటరిగా ఉండి విసుగొచ్చినప్పుడు ఒక అల్లరి ఆలోచన వచ్చింది.","‘తోడేలు! తోడేలు!’ అని కేక వేశాడు. గ్రామస్తులు పరుగెత్తుకుంటూ వచ్చారు. బాలుడు నవ్వుతుంటే వారు నిరాశగా వెళ్లిపోయారు.","అతడు మరుసటి రోజు కూడా అలాగే చేశాడు. మూడో రోజు నిజంగానే తోడేలు వచ్చింది. బాలుడు భయంతో సహాయం కోసం కేకలు వేశాడు.","ఈసారి ఎవరూ నమ్మలేదు. బాలుడు గొర్రెలను కాపాడేందుకు శ్రమించి, తరువాత గ్రామస్తులకు నిజం చెప్పి క్షమాపణ కోరాడు."],moral:"అబద్ధం చెప్పేవారి నిజాన్ని కూడా ప్రజలు నమ్మరు.",question:"బాలుడు మొదటిసారే నిజాయితీగా ఉంటే ఏమయ్యేది?",audio:["/audio/stories/boy-wolf-telugu-1.wav","/audio/stories/boy-wolf-telugu-2.wav","/audio/stories/boy-wolf-telugu-3.wav","/audio/stories/boy-wolf-telugu-4.wav","/audio/stories/boy-wolf-telugu-ending.wav"]},
    Hindi:{title:"भेड़िया आया कहने वाला लड़का",teaser:"झूठी पुकार ने सच्चे संकट को कठिन बना दिया।",pages:["एक चरवाहा लड़का रोज भेड़ों को पहाड़ी पर चराता था। अकेले बैठकर ऊब गया तो उसे शरारत सूझी।","उसने चिल्लाया, ‘भेड़िया! भेड़िया!’ गाँव वाले दौड़े आए। लड़के को हँसते देखकर वे निराश होकर लौट गए।","उसने अगले दिन फिर ऐसा किया। तीसरे दिन सच में भेड़िया आ गया। लड़का डरकर सहायता के लिए पुकारने लगा।","इस बार किसी ने विश्वास नहीं किया। लड़के ने भेड़ों को बचाने की कोशिश की और बाद में सच बताकर सबसे क्षमा माँगी।"],moral:"बार-बार झूठ बोलने वाले की सच्ची बात भी लोग नहीं मानते।",question:"यदि लड़का शुरू से सच बोलता तो क्या होता?",audio:["/audio/stories/boy-wolf-hindi-1.wav","/audio/stories/boy-wolf-hindi-2.wav","/audio/stories/boy-wolf-hindi-3.wav","/audio/stories/boy-wolf-hindi-4.wav","/audio/stories/boy-wolf-hindi-ending.wav"]}},
  { id:"ant-grasshopper", theme:"Planning", minutes:4,
    Telugu:{title:"చీమ మరియు మిడత",teaser:"ఈరోజు పని రేపటి కష్టాన్ని తగ్గించింది.",pages:["వేసవి రోజుల్లో చీమ గింజలను తన ఇంటికి మోసుకెళ్తూ ఉండేది. మిడత మాత్రం పాటలు పాడుతూ ఎండను ఆస్వాదించింది.","‘రా, ఆడుకుందాం,’ అంది మిడత. ‘వానాకాలానికి ఆహారం దాచాలి,’ అంటూ చీమ పని కొనసాగించింది.","వానలు మొదలయ్యాక మిడతకు తినడానికి ఏమీ దొరకలేదు. అది చీమ ఇంటి దగ్గరకు వచ్చి తన తప్పును ఒప్పుకుంది.","చీమ కొంత ఆహారం పంచి, తరువాత ఇద్దరూ కలిసి గింజలను సర్దారు. మిడత పని, ఆట రెండింటికీ సమయం పెట్టడం నేర్చుకుంది."],moral:"ముందుగా సిద్ధపడటం మనల్ని కష్టకాలంలో కాపాడుతుంది.",question:"పని మరియు ఆట రెండింటినీ ఎలా సమతుల్యం చేయవచ్చు?",audio:["/audio/stories/ant-grasshopper-telugu-1.wav","/audio/stories/ant-grasshopper-telugu-2.wav","/audio/stories/ant-grasshopper-telugu-3.wav","/audio/stories/ant-grasshopper-telugu-4.wav","/audio/stories/ant-grasshopper-telugu-ending.wav"]},
    Hindi:{title:"चींटी और टिड्डा",teaser:"आज की तैयारी ने कल की कठिनाई घटाई।",pages:["गर्मी में चींटी दाने अपने घर ले जाती रही। टिड्डा गीत गाता और धूप का आनंद लेता रहा।","टिड्डे ने कहा, ‘आओ खेलें।’ चींटी बोली, ‘बरसात के लिए भोजन बचाना है,’ और काम करती रही।","बारिश आई तो टिड्डे को भोजन नहीं मिला। वह चींटी के पास गया और अपनी गलती स्वीकार की।","चींटी ने कुछ भोजन बाँटा। फिर दोनों ने मिलकर दाने सँभाले। टिड्डे ने काम और खेल दोनों के लिए समय रखना सीखा।"],moral:"समय पर तैयारी कठिन दिनों में हमारी रक्षा करती है।",question:"काम और खेल में संतुलन कैसे रखा जा सकता है?",audio:["/audio/stories/ant-grasshopper-hindi-1.wav","/audio/stories/ant-grasshopper-hindi-2.wav","/audio/stories/ant-grasshopper-hindi-3.wav","/audio/stories/ant-grasshopper-hindi-4.wav","/audio/stories/ant-grasshopper-hindi-ending.wav"]}},
  { id:"crow-pitcher", theme:"Problem solving", minutes:3,
    Telugu:{title:"కాకి మరియు కుండ",teaser:"చిన్న రాళ్లు ఒక తెలివైన పరిష్కారం అయ్యాయి.",pages:["వేడి మధ్యాహ్నం ఒక కాకికి తీవ్రమైన దాహం వేసింది. చాలా సేపు వెతికాక కొద్దిగా నీరు ఉన్న కుండ కనిపించింది.","కుండలో నీరు చాలా దిగువన ఉండటంతో దాని ముక్కు అందలేదు. కుండను తోసినా, వంచినా ప్రయోజనం లేకపోయింది.","దగ్గరలో చిన్న రాళ్లను చూసిన కాకికి ఒక ఆలోచన వచ్చింది. ఒక్కొక్క రాయిని కుండలో వేసింది.","నీరు నెమ్మదిగా పైకి వచ్చింది. కాకి తాగి సంతోషంగా ఎగిరిపోయింది."],moral:"ఆలోచనతో కష్టమైన సమస్యకూ పరిష్కారం దొరుకుతుంది.",question:"రాళ్లు నీటిని పైకి ఎలా తెచ్చాయి?",audio:["/audio/stories/crow-pitcher-telugu-1.wav","/audio/stories/crow-pitcher-telugu-2.wav","/audio/stories/crow-pitcher-telugu-3.wav","/audio/stories/crow-pitcher-telugu-4.wav","/audio/stories/crow-pitcher-telugu-ending.wav"]},
    Hindi:{title:"कौआ और घड़ा",teaser:"छोटे कंकड़ एक समझदार उपाय बने।",pages:["गरम दोपहर में एक कौए को बहुत प्यास लगी। देर तक खोजने पर उसे थोड़ा पानी वाला घड़ा मिला।","पानी इतना नीचे था कि उसकी चोंच नहीं पहुँच सकी। घड़े को धकेलने और झुकाने से भी काम नहीं बना।","पास पड़े छोटे कंकड़ों को देखकर कौए को उपाय सूझा। उसने एक-एक कंकड़ घड़े में डाला।","पानी धीरे-धीरे ऊपर आया। कौए ने पानी पिया और प्रसन्न होकर उड़ गया।"],moral:"सोच-विचार से कठिन समस्या का हल मिल सकता है।",question:"कंकड़ों से पानी ऊपर कैसे आया?"}},
  { id:"dog-reflection", theme:"Contentment", minutes:3,
    Telugu:{title:"కుక్క మరియు దాని ప్రతిబింబం",teaser:"మరో రొట్టె ముక్క కోరగా తనదీ పోయింది.",pages:["ఒక కుక్కకు పెద్ద రొట్టె ముక్క దొరికింది. దానిని నోట పట్టుకుని వంతెన మీదుగా ఇంటికి బయలుదేరింది.","నీటిలో తన ప్రతిబింబాన్ని చూసి, మరో కుక్క ఇంకా పెద్ద రొట్టె ముక్క పట్టుకుందని భావించింది.","ఆ రొట్టె ముక్కను కూడా తీసుకోవాలని గట్టిగా మొరిగింది. నోరు తెరవగానే తన రొట్టె ముక్క నీటిలో పడిపోయింది.","అప్పుడు అది చూసింది మరొక కుక్క కాదని, తన ప్రతిబింబమేనని అర్థం చేసుకుంది."],moral:"అత్యాశ మన దగ్గర ఉన్నదానినీ పోగొట్టవచ్చు.",question:"కుక్క ఆగి ఆలోచించి ఉంటే ఏమయ్యేది?",audio:["/audio/stories/dog-reflection-telugu-1.wav","/audio/stories/dog-reflection-telugu-2.wav","/audio/stories/dog-reflection-telugu-3.wav","/audio/stories/dog-reflection-telugu-4.wav","/audio/stories/dog-reflection-telugu-ending.wav"]},
    Hindi:{title:"कुत्ता और उसकी परछाईं",teaser:"रोटी का दूसरा टुकड़ा चाहा और अपना भी खो दिया।",pages:["एक कुत्ते को रोटी का एक बड़ा टुकड़ा मिला। उसे मुँह में दबाकर वह पुल से घर जा रहा था।","पानी में अपनी परछाईं देखकर उसने समझा कि दूसरा कुत्ता रोटी का उससे भी बड़ा टुकड़ा लिए है।","वह दूसरा टुकड़ा लेने के लिए भौंका। मुँह खुलते ही उसकी रोटी पानी में गिर गई।","तब उसे समझ आया कि पानी में कोई दूसरा कुत्ता नहीं, उसकी अपनी परछाईं थी।"],moral:"लालच हमारे पास की वस्तु भी छीन सकता है।",question:"कुत्ता रुककर सोचता तो क्या होता?"}},
  { id:"two-mice", theme:"Contentment", minutes:4,
    Telugu:{title:"పల్లెటూరి ఎలుక మరియు పట్టణ ఎలుక",teaser:"విందు గొప్పదా, మనశ్శాంతి గొప్పదా?",pages:["పల్లెటూరి ఎలుక తన స్నేహితుడైన పట్టణ ఎలుకకు గింజలు, పండ్లు పెట్టింది. పట్టణ ఎలుక ఆ సాధారణ భోజనాన్ని చూసి నవ్వింది.","‘నాతో నగరానికి రా. అక్కడ ఎన్నో రుచులు ఉన్నాయి,’ అంది. ఇద్దరూ ఒక పెద్ద ఇంటి వంటగదికి చేరారు.","కేకులు తినబోతుండగా పిల్లి దూకింది. ఎలుకలు భయంతో అలమార వెనుక దాక్కున్నాయి. కొద్దిసేపటికే మనుషులు కూడా వచ్చారు.","పల్లెటూరి ఎలుక, ‘భయంతో విందు తినడం కంటే ప్రశాంతంగా గింజలు తినడమే మంచిది,’ అంటూ ఇంటికి తిరిగింది."],moral:"భద్రత, ప్రశాంతత ఆడంబరాలకంటే విలువైనవి.",question:"నువ్వు ఏ ఇంటిని ఎంచుకుంటావు? ఎందుకు?",audio:["/audio/stories/two-mice-telugu-1.wav","/audio/stories/two-mice-telugu-2.wav","/audio/stories/two-mice-telugu-3.wav","/audio/stories/two-mice-telugu-4.wav","/audio/stories/two-mice-telugu-ending.wav"]},
    Hindi:{title:"गाँव का चूहा और शहर का चूहा",teaser:"बड़ा भोज अच्छा या शांत मन?",pages:["गाँव के चूहे ने शहर के मित्र को दाने और फल खिलाए। शहर का चूहा साधारण भोजन देखकर हँसा।","उसने कहा, ‘मेरे साथ शहर चलो। वहाँ बहुत स्वादिष्ट खाना है।’ दोनों एक बड़े घर की रसोई पहुँचे।","वे केक खाने ही वाले थे कि बिल्ली झपटी। दोनों अलमारी के पीछे छिपे। थोड़ी देर में लोग भी आ गए।","गाँव का चूहा बोला, ‘डर के साथ भोज से अच्छा शांति से दाने खाना है,’ और घर लौट गया।"],moral:"सुरक्षा और शांति दिखावे से अधिक मूल्यवान हैं।",question:"तुम कौन-सा घर चुनते और क्यों?"}},
  { id:"golden-goose", theme:"Gratitude", minutes:4,
    Telugu:{title:"బంగారు గుడ్డు పెట్టే బాతు",teaser:"ప్రతి రోజు వచ్చిన వరాన్ని అత్యాశ ఆపేసింది.",pages:["ఒక రైతుకు ప్రతిరోజూ ఒక బంగారు గుడ్డు పెట్టే బాతు ఉండేది. ఒక్కో గుడ్డుతో అతని కుటుంబం సుఖంగా జీవించింది.","కొంతకాలానికి రైతు ఓపిక కోల్పోయాడు. బాతు లోపల అన్ని బంగారు గుడ్లు ఒకేసారి ఉంటాయని అనుకున్నాడు.","కానీ అతడు ఊహించిన బంగారం లోపల ఏమీ లేదు. అత్యాశతో బాతును కోల్పోయాడు.","తనకు ప్రతిరోజూ వచ్చిన అద్భుతమైన బహుమతిని గౌరవించలేదని రైతు బాధపడ్డాడు."],moral:"అత్యాశ వల్ల నిరంతరం లభించే మంచిని కోల్పోవచ్చు.",question:"రైతు కృతజ్ఞతతో ఉంటే అతని జీవితం ఎలా ఉండేది?",audio:["/audio/stories/golden-goose-telugu-1.wav","/audio/stories/golden-goose-telugu-2.wav","/audio/stories/golden-goose-telugu-3.wav","/audio/stories/golden-goose-telugu-4.wav","/audio/stories/golden-goose-telugu-ending.wav"]},
    Hindi:{title:"सोने का अंडा देने वाली हंस",teaser:"रोज मिलने वाला वरदान लालच ने रोक दिया।",pages:["एक किसान की हंस रोज सोने का एक अंडा देती थी। हर अंडे से उसका परिवार आराम से रहता था।","कुछ समय बाद किसान का धैर्य खत्म हो गया। उसने सोचा कि हंस के अंदर सारे सोने के अंडे एक साथ होंगे।","लालच में उसने हंस खो दी, पर अंदर वैसा कोई खज़ाना नहीं मिला।","किसान दुखी हुआ कि उसने रोज मिलने वाले अद्भुत उपहार का सम्मान नहीं किया।"],moral:"लालच से लगातार मिलने वाली अच्छी चीज भी खो सकती है।",question:"किसान कृतज्ञ रहता तो उसका जीवन कैसा होता?"}},
  { id:"wind-sun", theme:"Gentleness", minutes:3,
    Telugu:{title:"గాలి మరియు సూర్యుడు",teaser:"బలం చేయలేనిదాన్ని వెచ్చదనం చేసింది.",pages:["తమలో ఎవరు బలవంతులో గాలి, సూర్యుడు వాదించుకున్నారు. దారిలో కోటు వేసుకున్న ప్రయాణికుడిని చూశారు.","అతని కోటును ఎవరు తీయించగలరో వారే బలవంతులని నిర్ణయించారు. గాలి బలంగా వీచింది.","గాలి పెరిగే కొద్దీ ప్రయాణికుడు కోటును ఇంకా గట్టిగా పట్టుకున్నాడు. చివరకు గాలి అలసిపోయింది.","సూర్యుడు మృదువుగా వెచ్చని కిరణాలు పంపాడు. ప్రయాణికుడు చిరునవ్వుతో కోటును తానే తీసేశాడు."],moral:"కఠినత కంటే మృదుత్వం ఎక్కువ సాధించగలదు.",question:"ప్రయాణికుడు సూర్యుడి కోసం కోటు ఎందుకు తీశాడు?",audio:["/audio/stories/wind-sun-telugu-1.wav","/audio/stories/wind-sun-telugu-2.wav","/audio/stories/wind-sun-telugu-3.wav","/audio/stories/wind-sun-telugu-4.wav","/audio/stories/wind-sun-telugu-ending.wav"]},
    Hindi:{title:"हवा और सूरज",teaser:"जो बल न कर सका, वह गर्माहट ने कर दिया।",pages:["हवा और सूरज बहस कर रहे थे कि कौन अधिक शक्तिशाली है। उन्होंने कोट पहने एक यात्री को देखा।","उन्होंने तय किया कि जो उसका कोट उतरवाएगा वही शक्तिशाली होगा। हवा पूरी ताकत से चली।","हवा जितनी तेज हुई, यात्री ने कोट उतना कसकर पकड़ लिया। अंत में हवा थक गई।","सूरज ने धीरे से गरम किरणें भेजीं। यात्री मुस्कराया और स्वयं कोट उतार दिया।"],moral:"कठोरता से अधिक काम नम्रता कर सकती है।",question:"यात्री ने सूरज के समय कोट क्यों उतारा?"}},
  { id:"fox-stork", theme:"Respect", minutes:4,
    Telugu:{title:"నక్క మరియు కొంగ",teaser:"మనకు నచ్చే విధానం అందరికీ సరిపోదు.",pages:["నక్క కొంగను భోజనానికి పిలిచి, పలుచని పళ్లెంలో సూపు పెట్టింది. నక్క సులభంగా నాకి తాగింది.","పొడవైన ముక్కు ఉన్న కొంగకు ఒక్క చుక్క కూడా తాగడం సాధ్యం కాలేదు. నక్క మాత్రం దాని ఇబ్బందిని చూసి నవ్వింది.","కొంగ మరుసటి రోజు నక్కను పిలిచి పొడవైన సన్నని కూజాలో భోజనం పెట్టింది. కొంగ తినగలిగింది, నక్క తినలేకపోయింది.","నక్కకు తన తప్పు అర్థమైంది. ఇద్దరూ క్షమాపణ చెప్పుకుని, తరువాత అందరికీ సరిపోయే పాత్రల్లో భోజనం పంచుకున్నారు."],moral:"ఇతరులను మనం కోరుకునే గౌరవంతో చూడాలి.",question:"ఇద్దరూ మొదట ఏ పాత్రను ఎంచుకోవాల్సింది?",audio:["/audio/stories/fox-stork-telugu-1.wav","/audio/stories/fox-stork-telugu-2.wav","/audio/stories/fox-stork-telugu-3.wav","/audio/stories/fox-stork-telugu-4.wav","/audio/stories/fox-stork-telugu-ending.wav"]},
    Hindi:{title:"लोमड़ी और सारस",teaser:"जो तरीका हमें ठीक लगे, वह सबके लिए ठीक नहीं।",pages:["लोमड़ी ने सारस को बुलाकर चपटे बर्तन में सूप दिया। लोमड़ी ने आसानी से चाटकर पी लिया।","लंबी चोंच वाला सारस एक बूँद भी न पी सका। लोमड़ी उसकी कठिनाई देखकर हँसी।","अगले दिन सारस ने लोमड़ी को बुलाया और लंबी पतली सुराही में भोजन दिया। सारस खा सका, लोमड़ी नहीं।","लोमड़ी को अपनी गलती समझ आई। दोनों ने क्षमा माँगी और आगे से सबके अनुकूल बर्तनों में भोजन बाँटा।"],moral:"दूसरों के साथ वैसा व्यवहार करें जैसा हम अपने लिए चाहते हैं।",question:"दोनों को शुरू में कैसा बर्तन चुनना चाहिए था?"}},
  { id:"bundle-sticks", theme:"Teamwork", minutes:4,
    Telugu:{title:"కట్టెల కట్ట",teaser:"కలిసి ఉన్నప్పుడు బలం పెరుగుతుంది.",pages:["ఒక రైతు పిల్లలు చిన్న విషయాలకే గొడవపడేవారు. వారు కలిసి ఉండాలని రైతు కోరుకున్నాడు.","అతడు వారికి కట్టెల కట్ట ఇచ్చి విరవమన్నాడు. ఒక్కొక్కరు ప్రయత్నించినా కట్ట విరగలేదు.","తరువాత కట్ట విప్పి ఒక్కో కర్రను ఇచ్చాడు. పిల్లలు వాటిని సులభంగా విరిచారు.","‘కలిసి ఉంటే ఈ కట్టలా బలంగా ఉంటారు,’ అన్నాడు రైతు. పిల్లలు ఒకరికి ఒకరు తోడుగా ఉండాలని నిర్ణయించారు."],moral:"ఐకమత్యంలో బలం ఉంది.",question:"కట్టలోని కర్రలు ఎందుకు విరగలేదు?",audio:["/audio/stories/bundle-sticks-telugu-1.wav","/audio/stories/bundle-sticks-telugu-2.wav","/audio/stories/bundle-sticks-telugu-3.wav","/audio/stories/bundle-sticks-telugu-4.wav","/audio/stories/bundle-sticks-telugu-ending.wav"]},
    Hindi:{title:"लकड़ियों का गट्ठर",teaser:"साथ रहने से शक्ति बढ़ती है।",pages:["एक किसान के बच्चे छोटी-छोटी बातों पर झगड़ते थे। किसान चाहता था कि वे मिलकर रहें।","उसने लकड़ियों का गट्ठर देकर तोड़ने को कहा। सबने कोशिश की, पर गट्ठर नहीं टूटा।","फिर उसने गट्ठर खोलकर एक-एक लकड़ी दी। बच्चों ने उन्हें आसानी से तोड़ दिया।","किसान बोला, ‘साथ रहोगे तो इस गट्ठर जैसे मजबूत रहोगे।’ बच्चों ने एक-दूसरे का साथ देने का निश्चय किया।"],moral:"एकता में शक्ति होती है।",question:"गट्ठर की लकड़ियाँ क्यों नहीं टूटीं?"}},
  { id:"shepherd-goat", theme:"Loyalty", minutes:3,
    Telugu:{title:"కాపరి మరియు అడవి మేక",teaser:"కొత్తవారి కోసం పాత స్నేహాన్ని మర్చిపోవద్దు.",pages:["ఒక తుఫాను రోజున కొన్ని అడవి మేకలు కాపరి మందలో చేరాయి. కాపరి వాటిని ఉంచుకోవాలని ఆశపడ్డాడు.","తన మేకలకంటే అడవి మేకలకు ఎక్కువ ఆహారం పెట్టాడు. పాత మేకలు ఆకలిగా, నిర్లక్ష్యంగా అనిపించుకున్నాయి.","వాతావరణం బాగైన వెంటనే అడవి మేకలు కొండల్లోకి తిరిగి వెళ్లిపోయాయి. కాపరి వాటిని ఆపలేకపోయాడు.","తనతో ఎప్పటినుంచో ఉన్న మేకలను నిర్లక్ష్యం చేయడం తప్పని కాపరి గ్రహించి వాటిని ప్రేమగా చూసుకున్నాడు."],moral:"కొత్త పరిచయాల కోసం నమ్మకమైన స్నేహితులను మర్చిపోకూడదు.",question:"కాపరి తన మేకలకు ఎలా న్యాయం చేయగలిగేవాడు?",audio:["/audio/stories/shepherd-goat-telugu-1.wav","/audio/stories/shepherd-goat-telugu-2.wav","/audio/stories/shepherd-goat-telugu-3.wav","/audio/stories/shepherd-goat-telugu-4.wav","/audio/stories/shepherd-goat-telugu-ending.wav"]},
    Hindi:{title:"चरवाहा और जंगली बकरियाँ",teaser:"नए लोगों के लिए पुराने मित्रों को न भूलें।",pages:["तूफान के दिन कुछ जंगली बकरियाँ चरवाहे के झुंड में आ गईं। वह उन्हें अपने पास रखना चाहता था।","उसने अपनी बकरियों से अधिक भोजन जंगली बकरियों को दिया। पुरानी बकरियाँ भूखी और उपेक्षित महसूस करने लगीं।","मौसम साफ होते ही जंगली बकरियाँ पहाड़ों में लौट गईं। चरवाहा उन्हें रोक न सका।","उसे समझ आया कि पुराने साथियों की उपेक्षा करना गलत था। उसने अपनी बकरियों की फिर प्रेम से देखभाल की।"],moral:"नए परिचय के लिए भरोसेमंद मित्रों को नहीं भूलना चाहिए।",question:"चरवाहा सभी बकरियों के साथ न्याय कैसे करता?"}},
  { id:"peacock-crane", theme:"Self worth", minutes:3,
    Telugu:{title:"నెమలి మరియు కొంగ",teaser:"అందం ఒక్కటే ప్రతిభ కాదు.",pages:["నెమలి తన రంగురంగుల ఈకలను చూపిస్తూ కొంగ ముందు గర్వంగా నాట్యం చేసింది.","‘నా ఈకలు ఎంత అందంగా ఉన్నాయో చూడు. నీ బూడిద రంగు రెక్కలు చాలా సాధారణం,’ అంది.","కొంగ ప్రశాంతంగా తన రెక్కలను విప్పి ఆకాశంలోకి ఎగిరింది. నది, పొలాల మీదుగా ఎంతో దూరం ప్రయాణించింది.","‘నీ ఈకలు అందమైనవి. నా రెక్కలు నన్ను దూరాలకు తీసుకెళ్తాయి. ప్రతి ఒక్కరికీ ప్రత్యేకమైన బలం ఉంటుంది,’ అంది కొంగ."],moral:"మన విలువను రూపం ఒక్కటే నిర్ణయించదు.",question:"నెమలి, కొంగ—ఇద్దరిలో ఉన్న ప్రత్యేకతలు ఏమిటి?",audio:["/audio/stories/peacock-crane-telugu-1.wav","/audio/stories/peacock-crane-telugu-2.wav","/audio/stories/peacock-crane-telugu-3.wav","/audio/stories/peacock-crane-telugu-4.wav","/audio/stories/peacock-crane-telugu-ending.wav"]},
    Hindi:{title:"मोर और सारस",teaser:"सुंदरता ही एकमात्र गुण नहीं है।",pages:["मोर ने रंग-बिरंगे पंख दिखाते हुए सारस के सामने गर्व से नृत्य किया।","वह बोला, ‘मेरे पंख कितने सुंदर हैं। तुम्हारे भूरे पंख बहुत साधारण हैं।’","सारस ने शांत होकर पंख फैलाए और आकाश में उड़ गया। वह नदी और खेतों के ऊपर बहुत दूर तक गया।","सारस बोला, ‘तुम्हारे पंख सुंदर हैं। मेरे पंख मुझे दूर ले जाते हैं। हर किसी की अपनी विशेष शक्ति है।’"],moral:"हमारा मूल्य केवल रूप से तय नहीं होता।",question:"मोर और सारस की अलग-अलग विशेषताएँ क्या थीं?"}},
  { id:"wolf-crane", theme:"Wisdom", minutes:3,
    Telugu:{title:"తోడేలు మరియు కొంగ",teaser:"ప్రమాదకరమైన వాగ్దానాన్ని జాగ్రత్తగా చూడాలి.",pages:["ఒక తోడేలు గొంతులో ఎముక ఇరుక్కుంది. దాన్ని తీసేవారికి బహుమతి ఇస్తానని అడవంతా ప్రకటించింది.","పొడవైన ముక్కు ఉన్న కొంగ ధైర్యంగా ఎముకను తీసింది. తరువాత తన బహుమతి అడిగింది.","తోడేలు నవ్వి, ‘నా నోటిలో తల పెట్టి సురక్షితంగా బయటపడ్డావు—అదే నీ బహుమతి,’ అంది.","కొంగ దూరంగా ఎగిరి, నమ్మకంలేని వారి మాటలను జాగ్రత్తగా పరిశీలించాలని నేర్చుకుంది."],moral:"నమ్మకంలేని వారి వాగ్దానాలపై ఆధారపడకూడదు.",question:"కొంగ ముందుగానే ఏ జాగ్రత్త తీసుకోవచ్చు?",audio:["/audio/stories/wolf-crane-telugu-1.wav","/audio/stories/wolf-crane-telugu-2.wav","/audio/stories/wolf-crane-telugu-3.wav","/audio/stories/wolf-crane-telugu-4.wav","/audio/stories/wolf-crane-telugu-ending.wav"]},
    Hindi:{title:"भेड़िया और सारस",teaser:"खतरनाक वादे को सावधानी से समझना चाहिए।",pages:["एक भेड़िए के गले में हड्डी फँस गई। उसने घोषणा की कि हड्डी निकालने वाले को पुरस्कार देगा।","लंबी चोंच वाले सारस ने साहस से हड्डी निकाल दी। फिर उसने अपना पुरस्कार माँगा।","भेड़िया हँसा, ‘मेरे मुँह में सिर डालकर सुरक्षित निकल आए—यही पुरस्कार है।’","सारस दूर उड़ गया और उसने सीखा कि अविश्वसनीय व्यक्ति के वादे को सावधानी से जाँचना चाहिए।"],moral:"जिस पर भरोसा न हो, उसके वादे पर निर्भर नहीं होना चाहिए।",question:"सारस पहले कौन-सी सावधानी रख सकता था?"}},
  { id:"milkmaid-pail", theme:"Focus", minutes:4,
    Telugu:{title:"పాలకుండ మోసిన అమ్మాయి",teaser:"కలల్లో మునిగి అడుగును మర్చిపోయింది.",pages:["ఒక అమ్మాయి తలపై పాలకుండ పెట్టుకుని మార్కెట్‌కు నడిచింది. పాలు అమ్మి గుడ్లు కొనాలని అనుకుంది.","గుడ్ల నుంచి కోళ్లు వస్తాయని, వాటిని అమ్మి కొత్త దుస్తులు కొనాలని కలలు కంది. అందరూ తనను మెచ్చుకుంటారని ఊహించింది.","గర్వంగా తల ఊపగానే కుండ కిందపడింది. పాలు నేలపై పారిపోయాయి; ఊహించిన కోళ్లు, దుస్తులు అన్నీ మాయమయ్యాయి.","ఆమె లోతుగా ఊపిరి తీసుకుని ఇంటికి వెళ్లింది. తరువాతసారి కలలు కనడంతో పాటు తన అడుగులపై కూడా శ్రద్ధ పెట్టింది."],moral:"భవిష్యత్తు కలలతో పాటు ప్రస్తుత పనిపై దృష్టి పెట్టాలి.",question:"కలలు కనడం, జాగ్రత్తగా ఉండడం రెండూ ఎలా చేయవచ్చు?",audio:["/audio/stories/milkmaid-pail-telugu-1.wav","/audio/stories/milkmaid-pail-telugu-2.wav","/audio/stories/milkmaid-pail-telugu-3.wav","/audio/stories/milkmaid-pail-telugu-4.wav","/audio/stories/milkmaid-pail-telugu-ending.wav"]},
    Hindi:{title:"दूधवाली और उसका घड़ा",teaser:"सपनों में खोकर वह अपना कदम भूल गई।",pages:["एक लड़की सिर पर दूध का घड़ा रखकर बाज़ार चली। उसने सोचा, दूध बेचकर अंडे खरीदेगी।","अंडों से मुर्गियाँ होंगी, उन्हें बेचकर नए कपड़े खरीदेगी। उसने कल्पना की कि सब उसकी प्रशंसा करेंगे।","गर्व से सिर हिलाते ही घड़ा गिर गया। दूध बह गया और कल्पना की मुर्गियाँ व कपड़े भी चले गए।","वह गहरी साँस लेकर घर लौटी। अगली बार उसने सपने देखने के साथ अपने कदमों पर भी ध्यान दिया।"],moral:"भविष्य के सपनों के साथ वर्तमान काम पर ध्यान देना चाहिए।",question:"हम सपना भी कैसे देखें और सावधान भी रहें?"}},
  { id:"lion-rabbit", theme:"Courage", minutes:4,
    Telugu:{title:"సింహం మరియు తెలివైన కుందేలు",teaser:"చిన్న కుందేలు తెలివితో అడవిని కాపాడింది.",pages:["ఒక క్రూరమైన సింహం ప్రతిరోజూ అడవి జంతువులను భయపెట్టేది. అందరూ కలసి దాన్ని ఆపే మార్గం ఆలోచించారు.","చిన్న కుందేలు సింహం వద్దకు ఆలస్యంగా వెళ్లి, ‘మరో సింహం నన్ను అడ్డుకుంది,’ అంది. కోపంతో సింహం దానిని చూపమంది.","కుందేలు సింహాన్ని లోతైన బావి దగ్గరకు తీసుకెళ్లింది. నీటిలో తన ప్రతిబింబాన్ని చూసిన సింహం అది ప్రత్యర్థి అనుకుంది.","గర్జిస్తూ బావిలోకి దూకింది. జంతువులు కుందేలు తెలివి, ధైర్యాన్ని చూసి ఆనందించాయి."],moral:"తెలివి, ధైర్యం శారీరక బలాన్ని మించగలవు.",question:"కుందేలు బలాన్ని కాకుండా ఏది ఉపయోగించింది?",audio:["/audio/stories/lion-rabbit-telugu-1.wav","/audio/stories/lion-rabbit-telugu-2.wav","/audio/stories/lion-rabbit-telugu-3.wav","/audio/stories/lion-rabbit-telugu-4.wav","/audio/stories/lion-rabbit-telugu-ending.wav"]},
    Hindi:{title:"शेर और चतुर खरगोश",teaser:"छोटे खरगोश ने बुद्धि से जंगल बचाया।",pages:["एक क्रूर शेर रोज जंगल के जानवरों को डराता था। सबने मिलकर उसे रोकने का उपाय सोचा।","छोटा खरगोश देर से शेर के पास गया और बोला, ‘एक दूसरे शेर ने मुझे रोका।’ क्रोधित शेर ने उसे दिखाने को कहा।","खरगोश उसे गहरे कुएँ के पास ले गया। पानी में अपनी परछाईं देखकर शेर ने उसे प्रतिद्वंद्वी समझा।","वह दहाड़ते हुए कुएँ में कूद गया। जानवरों ने खरगोश की बुद्धि और साहस की प्रशंसा की।"],moral:"बुद्धि और साहस शारीरिक बल से आगे निकल सकते हैं।",question:"खरगोश ने बल के बदले किसका उपयोग किया?"}},
  { id:"travelers-bear", theme:"Friendship", minutes:4,
    Telugu:{title:"ఇద్దరు ప్రయాణికులు మరియు ఎలుగుబంటి",teaser:"కష్టంలో నిలిచేవాడే నిజమైన స్నేహితుడు.",pages:["ఇద్దరు స్నేహితులు అడవి దారిలో కలిసి నడిచారు. ఏ ప్రమాదం వచ్చినా ఒకరికి ఒకరు తోడుగా ఉంటామని మాట ఇచ్చుకున్నారు.","అకస్మాత్తుగా ఎలుగుబంటి వచ్చింది. ఒకడు వెంటనే చెట్టు ఎక్కాడు; తన స్నేహితుడిని కిందనే వదిలేశాడు.","చెట్టు ఎక్కలేని వాడు నేలపై ఊపిరి బిగపట్టి పడుకున్నాడు. ఎలుగుబంటి వాసన చూసి అతడు చనిపోయాడని భావించి వెళ్లిపోయింది.","కిందికి వచ్చిన స్నేహితుడు, ‘ఎలుగుబంటి ఏం చెప్పింది?’ అన్నాడు. ‘కష్టంలో వదిలే వారిని నమ్మవద్దంది,’ అని సమాధానం వచ్చింది."],moral:"కష్టకాలంలో తోడుగా ఉండేవాడే నిజమైన స్నేహితుడు.",question:"చెట్టు ఎక్కిన ప్రయాణికుడు ఏం చేయాల్సింది?",audio:["/audio/stories/travelers-bear-telugu-1.wav","/audio/stories/travelers-bear-telugu-2.wav","/audio/stories/travelers-bear-telugu-3.wav","/audio/stories/travelers-bear-telugu-4.wav","/audio/stories/travelers-bear-telugu-ending.wav"]},
    Hindi:{title:"दो यात्री और भालू",teaser:"मुसीबत में साथ रहने वाला ही सच्चा मित्र है।",pages:["दो मित्र जंगल के रास्ते साथ चल रहे थे। उन्होंने वादा किया कि संकट में एक-दूसरे की सहायता करेंगे।","अचानक भालू आया। एक व्यक्ति तुरंत पेड़ पर चढ़ गया और मित्र को नीचे छोड़ दिया।","पेड़ न चढ़ सकने वाला व्यक्ति साँस रोककर भूमि पर लेट गया। भालू ने सूँघा और उसे मृत समझकर चला गया।","नीचे उतरकर मित्र ने पूछा, ‘भालू ने क्या कहा?’ उत्तर मिला, ‘जो संकट में छोड़ दे, उस पर भरोसा मत करना।’"],moral:"कठिन समय में साथ देने वाला ही सच्चा मित्र है।",question:"पेड़ पर चढ़े यात्री को क्या करना चाहिए था?"}},
  { id:"hare-friends", theme:"Friendship", minutes:4,
    Telugu:{title:"కుందేలు మరియు అనేక స్నేహితులు",teaser:"మాటల కంటే నిజమైన సహాయం ముఖ్యం.",pages:["ఒక కుందేలు తనకు అడవిలో ఎన్నో స్నేహితులు ఉన్నారని గర్వపడేది. ప్రతి జంతువుతో ముచ్చటించేది.","ఒక రోజు వేట కుక్కలు దానిని వెంబడించాయి. కుందేలు గుర్రం, ఎద్దు, మేకను సహాయం అడిగింది.","ప్రతి ఒక్కరూ ఏదో కారణం చెప్పి, ‘మరో స్నేహితుడిని అడుగు,’ అన్నారు. కుందేలు నిరాశపడినా ఆలోచించడం ఆపలేదు.","అది ముళ్ల పొదలో దాక్కుని కుక్కలు వెళ్లేవరకు నిశ్శబ్దంగా ఉంది. నిజమైన స్నేహం మాటల్లో కాదు, పనుల్లో కనిపిస్తుందని నేర్చుకుంది."],moral:"స్నేహితుల సంఖ్య కంటే వారి నిజమైన తోడు ముఖ్యం.",question:"నిజమైన స్నేహితుడు ఎలా ప్రవర్తిస్తాడు?",audio:["/audio/stories/hare-friends-telugu-1.wav","/audio/stories/hare-friends-telugu-2.wav","/audio/stories/hare-friends-telugu-3.wav","/audio/stories/hare-friends-telugu-4.wav","/audio/stories/hare-friends-telugu-ending.wav"]},
    Hindi:{title:"खरगोश और उसके अनेक मित्र",teaser:"बातों से अधिक सच्ची सहायता महत्वपूर्ण है।",pages:["एक खरगोश गर्व करता था कि जंगल में उसके बहुत मित्र हैं। वह हर जानवर से मीठी बातें करता था।","एक दिन शिकारी कुत्ते उसके पीछे आए। उसने घोड़े, बैल और बकरी से सहायता माँगी।","सबने कोई कारण बताकर कहा, ‘किसी दूसरे मित्र से पूछो।’ खरगोश निराश हुआ, लेकिन सोचता रहा।","वह काँटेदार झाड़ी में चुपचाप छिप गया। उसने सीखा कि सच्ची मित्रता बातों में नहीं, काम में दिखाई देती है।"],moral:"मित्रों की संख्या से अधिक उनका सच्चा साथ महत्वपूर्ण है।",question:"सच्चा मित्र किस तरह व्यवहार करता है?"}},
  { id:"honest-woodcutter", theme:"Honesty", minutes:4,
    Telugu:{title:"నిజాయితీ గల కట్టెలవాడు",teaser:"నిజం చెప్పినందుకు అతనికి గొప్ప బహుమతి లభించింది.",pages:["ఒక పేద కట్టెలవాడు నది ఒడ్డున చెట్టు నరుకుతుండగా అతని ఇనుప గొడ్డలి నీటిలో పడిపోయింది.","నది దేవత బంగారు గొడ్డలి చూపి, ‘ఇది నీదా?’ అని అడిగింది. అతడు ‘కాదు’ అన్నాడు. ఆ తర్వాత వెండి గొడ్డలినీ చూపించింది. అతడు అది కూడా తనది కాదన్నాడు.","చివరకు ఇనుప గొడ్డలి కనిపించగానే, ‘అదే నాది!’ అని ఆనందంగా చెప్పాడు.","అతని నిజాయితీకి మెచ్చిన దేవత మూడు గొడ్డళ్లనూ బహుమతిగా ఇచ్చింది. కట్టెలవాడు కృతజ్ఞతతో ఇంటికి వెళ్లాడు."],moral:"నిజాయితీకి విలువైన ప్రతిఫలం లభిస్తుంది.",question:"కట్టెలవాడు బంగారు గొడ్డలిని ఎందుకు తీసుకోలేదు?",audio:["/audio/stories/honest-woodcutter-telugu-1.wav","/audio/stories/honest-woodcutter-telugu-2.wav","/audio/stories/honest-woodcutter-telugu-3.wav","/audio/stories/honest-woodcutter-telugu-4.wav","/audio/stories/honest-woodcutter-telugu-ending.wav"]},
    Hindi:{title:"ईमानदार लकड़हारा",teaser:"सच बोलने पर उसे अनमोल पुरस्कार मिला।",pages:["एक गरीब लकड़हारा नदी किनारे पेड़ काट रहा था। उसकी लोहे की कुल्हाड़ी पानी में गिर गई।","नदी देवी ने सोने की कुल्हाड़ी दिखाकर पूछा, ‘क्या यह तुम्हारी है?’ उसने ‘नहीं’ कहा। चाँदी की कुल्हाड़ी को भी अपना नहीं बताया।","अंत में लोहे की कुल्हाड़ी देखकर वह प्रसन्न हुआ, ‘यही मेरी है!’","उसकी ईमानदारी से प्रसन्न होकर देवी ने तीनों कुल्हाड़ियाँ दे दीं। लकड़हारा कृतज्ञ होकर घर लौटा।"],moral:"ईमानदारी का मूल्यवान फल मिलता है।",question:"लकड़हारे ने सोने की कुल्हाड़ी क्यों नहीं ली?"}}
];

const labels = {
  Telugu:{garden:"✦ ఈసప్ కథల తోట",heading:"ఇరవై చిన్న కథలు.",em:"మరొక కథ వినాలా?",intro:"తెలివి, దయ, నిజాయితీ, స్నేహం నేర్పే 3–4 నిమిషాల తెలుగు కథలు.",all:"అన్నీ",read:"కథ చదవండి →",listen:"తెలుగులో వినండి",audio:"తెలుగు ఆడియోను ఇక్కడ జోడించవచ్చు",previous:"← వెనుక",next:"తరువాతి పేజీ →",again:"మళ్లీ చదవండి ↻",moral:"కథ నీతి",question:"మాట్లాడుకుందాం"},
  Hindi:{garden:"✦ ईसप की कहानी बगिया",heading:"बीस छोटी कहानियाँ।",em:"एक कहानी और?",intro:"बुद्धि, दया, ईमानदारी और मित्रता सिखाने वाली 3–4 मिनट की हिंदी कहानियाँ।",all:"सभी",read:"कहानी पढ़ें →",listen:"हिंदी में सुनें",audio:"हिंदी ऑडियो यहाँ जोड़ा जा सकता है",previous:"← पीछे",next:"अगला पन्ना →",again:"फिर से पढ़ें ↻",moral:"कहानी की सीख",question:"बात करें"}
};

export default function StoryGarden() {
  const [language,setLanguage]=useState<Language>("Telugu");
  const [theme,setTheme]=useState("All");
  const [selected,setSelected]=useState<Story|null>(null);
  const [page,setPage]=useState(0);
  const [audioNotice,setAudioNotice]=useState(false);
  const [playing,setPlaying]=useState(false);
  const audioRef=useRef<HTMLAudioElement|null>(null);
  const l=labels[language];
  const themes=["All","Kindness","Honesty","Friendship","Courage","Teamwork","Wisdom"];
  const shown=theme==="All"?stories:stories.filter(story=>story.theme===theme);
  const selectedIndex=selected?stories.indexOf(selected):-1;
  const copy=selected?selected[language]:null;
  const currentAudio=copy?.audio?.[page];
  function coverStyle(story:Story,index:number){return story.id==="wolf-crane"?{backgroundImage:"url('/images/wolf-crane-natural.png')",backgroundSize:"cover",backgroundPosition:"center"}:{backgroundPosition:`${(index%5)*25}% ${Math.floor(index/5)*33.333}%`};}
  function stopAudio(){if(audioRef.current){audioRef.current.pause();audioRef.current.currentTime=0;}setPlaying(false);}
  function openStory(story:Story){stopAudio();setSelected(story);setPage(0);setAudioNotice(false);setTimeout(()=>document.getElementById("story-reader")?.scrollIntoView({behavior:"smooth"}),50);}
  function changePage(next:number){stopAudio();setAudioNotice(false);setPage(next);}
  async function playCurrentAudio(){if(!currentAudio){setAudioNotice(true);return;}if(playing){stopAudio();return;}const audio=audioRef.current;if(!audio)return;audio.currentTime=0;setAudioNotice(false);try{await audio.play();setPlaying(true);}catch{setPlaying(false);setAudioNotice(true);}}
  useEffect(()=>()=>{audioRef.current?.pause()},[]);

  return <section className="story-garden" id="stories">
    <div className="story-heading"><div><h2>{language==="Telugu"?"కథా వనం":"कथा वन"}</h2></div><span><b>20</b><small>{language==="Telugu"?"చిత్ర కథలు":"चित्र कहानियाँ"}</small></span></div>
    <div className="story-language" role="group" aria-label="Story language"><button className={language==="Telugu"?"active":""} onClick={()=>{stopAudio();setLanguage("Telugu");setPage(0);setAudioNotice(false)}}>తెలుగు</button><button className={language==="Hindi"?"active":""} onClick={()=>{stopAudio();setLanguage("Hindi");setPage(0);setAudioNotice(false)}}>हिंदी</button></div>
    <div className="story-filters" role="group" aria-label="Filter stories">{themes.map(item=><button key={item} className={theme===item?"active":""} onClick={()=>setTheme(item)}>{item==="All"?l.all:item}</button>)}</div>
    <div className="story-grid">{shown.map(story=>{const index=stories.indexOf(story),c=story[language];return <button className="story-card" key={story.id} onClick={()=>openStory(story)}><span className="story-cover" style={coverStyle(story,index)}/><span className="story-card-copy"><small>{story.theme} · {story.minutes} min</small><b>{c.title}</b><i>{c.teaser}</i><strong>{l.read}</strong></span></button>})}</div>
    {selected&&copy&&<div className="story-reader" id="story-reader"><button className="reader-close" onClick={()=>{stopAudio();setSelected(null)}} aria-label="Close story">×</button><div className="reader-cover story-cover" style={coverStyle(selected,selectedIndex)}/><div className="reader-copy"><small>{selected.theme} · {page<copy.pages.length?`PAGE ${page+1} OF ${copy.pages.length}`:language==="Telugu"?"ముగింపు":"समापन"}</small><h3>{copy.title}</h3>{page<copy.pages.length?<p>{copy.pages[page]}</p>:<div className="story-ending"><h4>{l.moral}</h4><p>{copy.moral}</p><h4>{l.question}</h4><p>{copy.question}</p></div>}<audio ref={audioRef} src={currentAudio} onEnded={()=>setPlaying(false)} onError={()=>{setPlaying(false);setAudioNotice(true)}}/><button className={`story-audio-placeholder ${currentAudio?"has-audio":""}`} onClick={playCurrentAudio}>{playing?"■ ":"▶ "}{playing?(language==="Telugu"?"ఆపండి":"रोकें"):l.listen}</button>{audioNotice&&<small className="audio-notice">{currentAudio?(language==="Telugu"?"ఆడియో ప్లే కాలేదు. మళ్లీ ప్రయత్నించండి.":"ऑडियो नहीं चला। फिर कोशिश करें।"):l.audio}</small>}<div className="reader-progress"><i style={{width:`${((page+1)/(copy.pages.length+1))*100}%`}}/></div><div className="reader-actions"><button disabled={page===0} onClick={()=>changePage(page-1)}>{l.previous}</button><button onClick={()=>changePage(page===copy.pages.length?0:page+1)}>{page===copy.pages.length?l.again:l.next}</button></div></div></div>}
  </section>;
}
